export const ACCESS_COOKIE = "elms_access_token";
export const REFRESH_COOKIE = "elms_refresh_token";
export const LOCAL_SESSION_COOKIE = "elms_local_session";
export const LOCAL_SESSION_HEADER = "x-elms-session";

export const SYSTEM_ROLE_KEYS = {
  FIRM_ADMIN: "firm_admin",
  SENIOR_LAWYER: "senior_lawyer",
  JUNIOR_LAWYER: "junior_lawyer",
  PARALEGAL: "paralegal",
  SECRETARY: "secretary"
} as const;

export const DEFAULT_PERMISSIONS = [
  "firms:read",
  "settings:read",
  "settings:update",
  "users:create",
  "users:read",
  "users:update",
  "users:delete",
  "roles:read",
  "invitations:create",
  "invitations:read",
  "invitations:revoke",
  "cases:create",
  "cases:read",
  "cases:update",
  "cases:assign",
  "cases:status",
  "cases:delete",
  "clients:create",
  "clients:read",
  "clients:update",
  "clients:delete",
  "hearings:create",
  "hearings:read",
  "hearings:update",
  "hearings:delete",
  "tasks:create",
  "tasks:read",
  "tasks:update",
  "tasks:delete",
  "dashboard:read",
  "documents:create",
  "documents:read",
  "documents:update",
  "documents:delete",
  "reports:read",
  "research:use",
  "lookups:read",
  "lookups:manage",
  "roles:create",
  "roles:update",
  "roles:delete",
  "invoices:create",
  "invoices:read",
  "invoices:update",
  "invoices:delete",
  "expenses:create",
  "expenses:read",
  "expenses:update",
  "expenses:delete",
  "templates:create",
  "templates:read",
  "templates:update",
  "templates:delete",
  "library:read",
  "library:manage",
  "powers:create",
  "powers:read",
  "powers:update",
  "powers:delete",
  "powers:revoke"
];
