export interface GovernorateSeedRow {
  key: string;
  labelAr: string;
  labelEn: string;
  labelFr: string;
  sortOrder: number;
}

export interface CitySeedRow {
  governorateKey: string;
  key: string;
  labelAr: string;
  labelEn: string;
  labelFr: string;
}

export const EGYPT_GOVERNORATES: GovernorateSeedRow[] = [
  { key: "CAIRO", labelAr: "القاهرة", labelEn: "Cairo", labelFr: "Cairo", sortOrder: 0 },
  { key: "GIZA", labelAr: "الجيزة", labelEn: "Giza", labelFr: "Giza", sortOrder: 1 },
  { key: "ALEXANDRIA", labelAr: "الإسكندرية", labelEn: "Alexandria", labelFr: "Alexandria", sortOrder: 2 },
  { key: "DAKAHLIA", labelAr: "الدقهلية", labelEn: "Dakahlia", labelFr: "Dakahlia", sortOrder: 3 },
  { key: "RED_SEA", labelAr: "البحر الأحمر", labelEn: "Red Sea", labelFr: "Red Sea", sortOrder: 4 },
  { key: "BEHEIRA", labelAr: "البحيرة", labelEn: "Beheira", labelFr: "Beheira", sortOrder: 5 },
  { key: "FAYOUM", labelAr: "الفيوم", labelEn: "Fayoum", labelFr: "Fayoum", sortOrder: 6 },
  { key: "GHARBIYA", labelAr: "الغربية", labelEn: "Gharbiya", labelFr: "Gharbiya", sortOrder: 7 },
  { key: "ISMAILIA", labelAr: "الإسماعيلية", labelEn: "Ismailia", labelFr: "Ismailia", sortOrder: 8 },
  { key: "MONUFIA", labelAr: "المنوفية", labelEn: "Monufia", labelFr: "Monufia", sortOrder: 9 },
  { key: "MINYA", labelAr: "المنيا", labelEn: "Minya", labelFr: "Minya", sortOrder: 10 },
  { key: "QALIUBIYA", labelAr: "القليوبية", labelEn: "Qaliubiya", labelFr: "Qaliubiya", sortOrder: 11 },
  { key: "NEW_VALLEY", labelAr: "الوادي الجديد", labelEn: "New Valley", labelFr: "New Valley", sortOrder: 12 },
  { key: "SUEZ", labelAr: "السويس", labelEn: "Suez", labelFr: "Suez", sortOrder: 13 },
  { key: "ASWAN", labelAr: "أسوان", labelEn: "Aswan", labelFr: "Aswan", sortOrder: 14 },
  { key: "ASSIUT", labelAr: "أسيوط", labelEn: "Assiut", labelFr: "Assiut", sortOrder: 15 },
  { key: "BENI_SUEF", labelAr: "بني سويف", labelEn: "Beni Suef", labelFr: "Beni Suef", sortOrder: 16 },
  { key: "PORT_SAID", labelAr: "بورسعيد", labelEn: "Port Said", labelFr: "Port Said", sortOrder: 17 },
  { key: "DAMIETTA", labelAr: "دمياط", labelEn: "Damietta", labelFr: "Damietta", sortOrder: 18 },
  { key: "SHARKIA", labelAr: "الشرقية", labelEn: "Sharkia", labelFr: "Sharkia", sortOrder: 19 },
  { key: "SOUTH_SINAI", labelAr: "جنوب سيناء", labelEn: "South Sinai", labelFr: "South Sinai", sortOrder: 20 },
  { key: "KAFR_EL_SHEIKH", labelAr: "كفر الشيخ", labelEn: "Kafr El Sheikh", labelFr: "Kafr El Sheikh", sortOrder: 21 },
  { key: "MATROUH", labelAr: "مطروح", labelEn: "Matrouh", labelFr: "Matrouh", sortOrder: 22 },
  { key: "LUXOR", labelAr: "الأقصر", labelEn: "Luxor", labelFr: "Luxor", sortOrder: 23 },
  { key: "QENA", labelAr: "قنا", labelEn: "Qena", labelFr: "Qena", sortOrder: 24 },
  { key: "NORTH_SINAI", labelAr: "شمال سيناء", labelEn: "North Sinai", labelFr: "North Sinai", sortOrder: 25 },
  { key: "SOHAG", labelAr: "سوهاج", labelEn: "Sohag", labelFr: "Sohag", sortOrder: 26 },
];

export const EGYPT_CITIES: CitySeedRow[] = [
  { governorateKey: "CAIRO", key: "15_MAY", labelAr: "15 مايو", labelEn: "15 May", labelFr: "15 May" },
  { governorateKey: "CAIRO", key: "AL_AZBAKEYAH", labelAr: "الازبكية", labelEn: "Al Azbakeyah", labelFr: "Al Azbakeyah" },
  { governorateKey: "CAIRO", key: "AL_BASATIN", labelAr: "البساتين", labelEn: "Al Basatin", labelFr: "Al Basatin" },
  { governorateKey: "CAIRO", key: "TEBIN", labelAr: "التبين", labelEn: "Tebin", labelFr: "Tebin" },
  { governorateKey: "CAIRO", key: "EL-KHALIFA", labelAr: "الخليفة", labelEn: "El-Khalifa", labelFr: "El-Khalifa" },
  { governorateKey: "CAIRO", key: "EL_DARRASA", labelAr: "الدراسة", labelEn: "El darrasa", labelFr: "El darrasa" },
  { governorateKey: "CAIRO", key: "ALDARB_ALAHMAR", labelAr: "الدرب الاحمر", labelEn: "Aldarb Alahmar", labelFr: "Aldarb Alahmar" },
  { governorateKey: "CAIRO", key: "ZAWYA_AL-HAMRA", labelAr: "الزاوية الحمراء", labelEn: "Zawya al-Hamra", labelFr: "Zawya al-Hamra" },
  { governorateKey: "CAIRO", key: "EL-ZAYTOUN", labelAr: "الزيتون", labelEn: "El-Zaytoun", labelFr: "El-Zaytoun" },
  { governorateKey: "CAIRO", key: "SAHEL", labelAr: "الساحل", labelEn: "Sahel", labelFr: "Sahel" },
  { governorateKey: "CAIRO", key: "EL_SALAM", labelAr: "السلام", labelEn: "El Salam", labelFr: "El Salam" },
  { governorateKey: "CAIRO", key: "SAYEDA_ZEINAB", labelAr: "السيدة زينب", labelEn: "Sayeda Zeinab", labelFr: "Sayeda Zeinab" },
  { governorateKey: "CAIRO", key: "EL_SHARABEYA", labelAr: "الشرابية", labelEn: "El Sharabeya", labelFr: "El Sharabeya" },
  { governorateKey: "CAIRO", key: "SHOROUK", labelAr: "مدينة الشروق", labelEn: "Shorouk", labelFr: "Shorouk" },
  { governorateKey: "CAIRO", key: "EL_DAHER", labelAr: "الظاهر", labelEn: "El Daher", labelFr: "El Daher" },
  { governorateKey: "CAIRO", key: "ATABA", labelAr: "العتبة", labelEn: "Ataba", labelFr: "Ataba" },
  { governorateKey: "CAIRO", key: "NEW_CAIRO", labelAr: "القاهرة الجديدة", labelEn: "New Cairo", labelFr: "New Cairo" },
  { governorateKey: "CAIRO", key: "EL_MARG", labelAr: "المرج", labelEn: "El Marg", labelFr: "El Marg" },
  { governorateKey: "CAIRO", key: "EZBET_EL_NAKHL", labelAr: "عزبة النخل", labelEn: "Ezbet el Nakhl", labelFr: "Ezbet el Nakhl" },
  { governorateKey: "CAIRO", key: "MATAREYA", labelAr: "المطرية", labelEn: "Matareya", labelFr: "Matareya" },
  { governorateKey: "CAIRO", key: "MAADI", labelAr: "المعادى", labelEn: "Maadi", labelFr: "Maadi" },
  { governorateKey: "CAIRO", key: "MAASARA", labelAr: "المعصرة", labelEn: "Maasara", labelFr: "Maasara" },
  { governorateKey: "CAIRO", key: "MOKATTAM", labelAr: "المقطم", labelEn: "Mokattam", labelFr: "Mokattam" },
  { governorateKey: "CAIRO", key: "MANYAL", labelAr: "المنيل", labelEn: "Manyal", labelFr: "Manyal" },
  { governorateKey: "CAIRO", key: "MOSKY", labelAr: "الموسكى", labelEn: "Mosky", labelFr: "Mosky" },
  { governorateKey: "CAIRO", key: "NOZHA", labelAr: "النزهة", labelEn: "Nozha", labelFr: "Nozha" },
  { governorateKey: "CAIRO", key: "WAILY", labelAr: "الوايلى", labelEn: "Waily", labelFr: "Waily" },
  { governorateKey: "CAIRO", key: "BAB_AL-SHEREIA", labelAr: "باب الشعرية", labelEn: "Bab al-Shereia", labelFr: "Bab al-Shereia" },
  { governorateKey: "CAIRO", key: "BOLAQ", labelAr: "بولاق", labelEn: "Bolaq", labelFr: "Bolaq" },
  { governorateKey: "CAIRO", key: "GARDEN_CITY", labelAr: "جاردن سيتى", labelEn: "Garden City", labelFr: "Garden City" },
  { governorateKey: "CAIRO", key: "HADAYEK_EL-KOBBA", labelAr: "حدائق القبة", labelEn: "Hadayek El-Kobba", labelFr: "Hadayek El-Kobba" },
  { governorateKey: "CAIRO", key: "HELWAN", labelAr: "حلوان", labelEn: "Helwan", labelFr: "Helwan" },
  { governorateKey: "CAIRO", key: "DAR_AL_SALAM", labelAr: "دار السلام", labelEn: "Dar Al Salam", labelFr: "Dar Al Salam" },
  { governorateKey: "CAIRO", key: "SHUBRA", labelAr: "شبرا", labelEn: "Shubra", labelFr: "Shubra" },
  { governorateKey: "CAIRO", key: "TURA", labelAr: "طره", labelEn: "Tura", labelFr: "Tura" },
  { governorateKey: "CAIRO", key: "ABDEEN", labelAr: "عابدين", labelEn: "Abdeen", labelFr: "Abdeen" },
  { governorateKey: "CAIRO", key: "ABASEYA", labelAr: "عباسية", labelEn: "Abaseya", labelFr: "Abaseya" },
  { governorateKey: "CAIRO", key: "AIN_SHAMS", labelAr: "عين شمس", labelEn: "Ain Shams", labelFr: "Ain Shams" },
  { governorateKey: "CAIRO", key: "NASR_CITY", labelAr: "مدينة نصر", labelEn: "Nasr City", labelFr: "Nasr City" },
  { governorateKey: "CAIRO", key: "NEW_HELIOPOLIS", labelAr: "مصر الجديدة", labelEn: "New Heliopolis", labelFr: "New Heliopolis" },
  { governorateKey: "CAIRO", key: "MASR_AL_QADIMA", labelAr: "مصر القديمة", labelEn: "Masr Al Qadima", labelFr: "Masr Al Qadima" },
  { governorateKey: "CAIRO", key: "MANSHEYA_NASIR", labelAr: "منشية ناصر", labelEn: "Mansheya Nasir", labelFr: "Mansheya Nasir" },
  { governorateKey: "CAIRO", key: "BADR_CITY", labelAr: "مدينة بدر", labelEn: "Badr City", labelFr: "Badr City" },
  { governorateKey: "CAIRO", key: "OBOUR_CITY", labelAr: "مدينة العبور", labelEn: "Obour City", labelFr: "Obour City" },
  { governorateKey: "CAIRO", key: "CAIRO_DOWNTOWN", labelAr: "وسط البلد", labelEn: "Cairo Downtown", labelFr: "Cairo Downtown" },
  { governorateKey: "CAIRO", key: "ZAMALEK", labelAr: "الزمالك", labelEn: "Zamalek", labelFr: "Zamalek" },
  { governorateKey: "CAIRO", key: "KASR_EL_NILE", labelAr: "قصر النيل", labelEn: "Kasr El Nile", labelFr: "Kasr El Nile" },
  { governorateKey: "CAIRO", key: "REHAB", labelAr: "الرحاب", labelEn: "Rehab", labelFr: "Rehab" },
  { governorateKey: "CAIRO", key: "KATAMEYA", labelAr: "القطامية", labelEn: "Katameya", labelFr: "Katameya" },
  { governorateKey: "CAIRO", key: "MADINTY", labelAr: "مدينتي", labelEn: "Madinty", labelFr: "Madinty" },
  { governorateKey: "CAIRO", key: "ROD_ALFARAG", labelAr: "روض الفرج", labelEn: "Rod Alfarag", labelFr: "Rod Alfarag" },
  { governorateKey: "CAIRO", key: "SHERATON", labelAr: "شيراتون", labelEn: "Sheraton", labelFr: "Sheraton" },
  { governorateKey: "CAIRO", key: "EL-GAMALEYA", labelAr: "الجمالية", labelEn: "El-Gamaleya", labelFr: "El-Gamaleya" },
  { governorateKey: "CAIRO", key: "10TH_OF_RAMADAN_CITY", labelAr: "العاشر من رمضان", labelEn: "10th of Ramadan City", labelFr: "10th of Ramadan City" },
  { governorateKey: "CAIRO", key: "HELMEYAT_ALZAYTOUN", labelAr: "الحلمية", labelEn: "Helmeyat Alzaytoun", labelFr: "Helmeyat Alzaytoun" },
  { governorateKey: "CAIRO", key: "NEW_NOZHA", labelAr: "النزهة الجديدة", labelEn: "New Nozha", labelFr: "New Nozha" },
  { governorateKey: "CAIRO", key: "CAPITAL_NEW", labelAr: "العاصمة الإدارية", labelEn: "Capital New", labelFr: "Capital New" },
  { governorateKey: "GIZA", key: "GIZA", labelAr: "الجيزة", labelEn: "Giza", labelFr: "Giza" },
  { governorateKey: "GIZA", key: "SIXTH_OF_OCTOBER", labelAr: "السادس من أكتوبر", labelEn: "Sixth of October", labelFr: "Sixth of October" },
  { governorateKey: "GIZA", key: "SHEIKH_ZAYED", labelAr: "الشيخ زايد", labelEn: "Sheikh Zayed", labelFr: "Sheikh Zayed" },
  { governorateKey: "GIZA", key: "HAWAMDIYAH", labelAr: "الحوامدية", labelEn: "Hawamdiyah", labelFr: "Hawamdiyah" },
  { governorateKey: "GIZA", key: "AL_BADRASHEEN", labelAr: "البدرشين", labelEn: "Al Badrasheen", labelFr: "Al Badrasheen" },
  { governorateKey: "GIZA", key: "SAF", labelAr: "الصف", labelEn: "Saf", labelFr: "Saf" },
  { governorateKey: "GIZA", key: "ATFIH", labelAr: "أطفيح", labelEn: "Atfih", labelFr: "Atfih" },
  { governorateKey: "GIZA", key: "AL_AYAT", labelAr: "العياط", labelEn: "Al Ayat", labelFr: "Al Ayat" },
  { governorateKey: "GIZA", key: "AL-BAWAITI", labelAr: "الباويطي", labelEn: "Al-Bawaiti", labelFr: "Al-Bawaiti" },
  { governorateKey: "GIZA", key: "MANSHIYETAL_QANATER", labelAr: "منشأة القناطر", labelEn: "ManshiyetAl Qanater", labelFr: "ManshiyetAl Qanater" },
  { governorateKey: "GIZA", key: "OASEEM", labelAr: "أوسيم", labelEn: "Oaseem", labelFr: "Oaseem" },
  { governorateKey: "GIZA", key: "KERDASA", labelAr: "كرداسة", labelEn: "Kerdasa", labelFr: "Kerdasa" },
  { governorateKey: "GIZA", key: "ABU_NOMROS", labelAr: "أبو النمرس", labelEn: "Abu Nomros", labelFr: "Abu Nomros" },
  { governorateKey: "GIZA", key: "KAFR_GHATI", labelAr: "كفر غطاطي", labelEn: "Kafr Ghati", labelFr: "Kafr Ghati" },
  { governorateKey: "GIZA", key: "MANSHIYET_AL_BAKARI", labelAr: "منشأة البكاري", labelEn: "Manshiyet Al Bakari", labelFr: "Manshiyet Al Bakari" },
  { governorateKey: "GIZA", key: "DOKKI", labelAr: "الدقى", labelEn: "Dokki", labelFr: "Dokki" },
  { governorateKey: "GIZA", key: "AGOUZA", labelAr: "العجوزة", labelEn: "Agouza", labelFr: "Agouza" },
  { governorateKey: "GIZA", key: "HARAM", labelAr: "الهرم", labelEn: "Haram", labelFr: "Haram" },
  { governorateKey: "GIZA", key: "WARRAQ", labelAr: "الوراق", labelEn: "Warraq", labelFr: "Warraq" },
  { governorateKey: "GIZA", key: "IMBABA", labelAr: "امبابة", labelEn: "Imbaba", labelFr: "Imbaba" },
  { governorateKey: "GIZA", key: "BOULAQ_DAKROUR", labelAr: "بولاق الدكرور", labelEn: "Boulaq Dakrour", labelFr: "Boulaq Dakrour" },
  { governorateKey: "GIZA", key: "AL_WAHAT_AL_BAHARIA", labelAr: "الواحات البحرية", labelEn: "Al Wahat Al Baharia", labelFr: "Al Wahat Al Baharia" },
  { governorateKey: "GIZA", key: "OMRANEYA", labelAr: "العمرانية", labelEn: "Omraneya", labelFr: "Omraneya" },
  { governorateKey: "GIZA", key: "MONEEB", labelAr: "المنيب", labelEn: "Moneeb", labelFr: "Moneeb" },
  { governorateKey: "GIZA", key: "BIN_ALSARAYAT", labelAr: "بين السرايات", labelEn: "Bin Alsarayat", labelFr: "Bin Alsarayat" },
  { governorateKey: "GIZA", key: "KIT_KAT", labelAr: "الكيت كات", labelEn: "Kit Kat", labelFr: "Kit Kat" },
  { governorateKey: "GIZA", key: "MOHANDESSIN", labelAr: "المهندسين", labelEn: "Mohandessin", labelFr: "Mohandessin" },
  { governorateKey: "GIZA", key: "FAISAL", labelAr: "فيصل", labelEn: "Faisal", labelFr: "Faisal" },
  { governorateKey: "GIZA", key: "ABU_RAWASH", labelAr: "أبو رواش", labelEn: "Abu Rawash", labelFr: "Abu Rawash" },
  { governorateKey: "GIZA", key: "HADAYEK_ALAHRAM", labelAr: "حدائق الأهرام", labelEn: "Hadayek Alahram", labelFr: "Hadayek Alahram" },
  { governorateKey: "GIZA", key: "HARANEYA", labelAr: "الحرانية", labelEn: "Haraneya", labelFr: "Haraneya" },
  { governorateKey: "GIZA", key: "HADAYEK_OCTOBER", labelAr: "حدائق اكتوبر", labelEn: "Hadayek October", labelFr: "Hadayek October" },
  { governorateKey: "GIZA", key: "SAFT_ALLABAN", labelAr: "صفط اللبن", labelEn: "Saft Allaban", labelFr: "Saft Allaban" },
  { governorateKey: "GIZA", key: "SMART_VILLAGE", labelAr: "القرية الذكية", labelEn: "Smart Village", labelFr: "Smart Village" },
  { governorateKey: "GIZA", key: "ARD_ELLWAA", labelAr: "ارض اللواء", labelEn: "Ard Ellwaa", labelFr: "Ard Ellwaa" },
  { governorateKey: "ALEXANDRIA", key: "ABU_QIR", labelAr: "ابو قير", labelEn: "Abu Qir", labelFr: "Abu Qir" },
  { governorateKey: "ALEXANDRIA", key: "AL_IBRAHIMEYAH", labelAr: "الابراهيمية", labelEn: "Al Ibrahimeyah", labelFr: "Al Ibrahimeyah" },
  { governorateKey: "ALEXANDRIA", key: "AZARITA", labelAr: "الأزاريطة", labelEn: "Azarita", labelFr: "Azarita" },
  { governorateKey: "ALEXANDRIA", key: "ANFOUSHI", labelAr: "الانفوشى", labelEn: "Anfoushi", labelFr: "Anfoushi" },
  { governorateKey: "ALEXANDRIA", key: "DEKHEILA", labelAr: "الدخيلة", labelEn: "Dekheila", labelFr: "Dekheila" },
  { governorateKey: "ALEXANDRIA", key: "EL_SOYOF", labelAr: "السيوف", labelEn: "El Soyof", labelFr: "El Soyof" },
  { governorateKey: "ALEXANDRIA", key: "AMERIA", labelAr: "العامرية", labelEn: "Ameria", labelFr: "Ameria" },
  { governorateKey: "ALEXANDRIA", key: "EL_LABBAN", labelAr: "اللبان", labelEn: "El Labban", labelFr: "El Labban" },
  { governorateKey: "ALEXANDRIA", key: "AL_MAFROUZA", labelAr: "المفروزة", labelEn: "Al Mafrouza", labelFr: "Al Mafrouza" },
  { governorateKey: "ALEXANDRIA", key: "EL_MONTAZA", labelAr: "المنتزه", labelEn: "El Montaza", labelFr: "El Montaza" },
  { governorateKey: "ALEXANDRIA", key: "MANSHEYA", labelAr: "المنشية", labelEn: "Mansheya", labelFr: "Mansheya" },
  { governorateKey: "ALEXANDRIA", key: "NASERIA", labelAr: "الناصرية", labelEn: "Naseria", labelFr: "Naseria" },
  { governorateKey: "ALEXANDRIA", key: "AMBROZO", labelAr: "امبروزو", labelEn: "Ambrozo", labelFr: "Ambrozo" },
  { governorateKey: "ALEXANDRIA", key: "BAB_SHARQ", labelAr: "باب شرق", labelEn: "Bab Sharq", labelFr: "Bab Sharq" },
  { governorateKey: "ALEXANDRIA", key: "BOURJ_ALARAB", labelAr: "برج العرب", labelEn: "Bourj Alarab", labelFr: "Bourj Alarab" },
  { governorateKey: "ALEXANDRIA", key: "STANLEY", labelAr: "ستانلى", labelEn: "Stanley", labelFr: "Stanley" },
  { governorateKey: "ALEXANDRIA", key: "SMOUHA", labelAr: "سموحة", labelEn: "Smouha", labelFr: "Smouha" },
  { governorateKey: "ALEXANDRIA", key: "SIDI_BISHR", labelAr: "سيدى بشر", labelEn: "Sidi Bishr", labelFr: "Sidi Bishr" },
  { governorateKey: "ALEXANDRIA", key: "SHADS", labelAr: "شدس", labelEn: "Shads", labelFr: "Shads" },
  { governorateKey: "ALEXANDRIA", key: "GHEET_ALENAB", labelAr: "غيط العنب", labelEn: "Gheet Alenab", labelFr: "Gheet Alenab" },
  { governorateKey: "ALEXANDRIA", key: "FLEMING", labelAr: "فلمينج", labelEn: "Fleming", labelFr: "Fleming" },
  { governorateKey: "ALEXANDRIA", key: "VICTORIA", labelAr: "فيكتوريا", labelEn: "Victoria", labelFr: "Victoria" },
  { governorateKey: "ALEXANDRIA", key: "CAMP_SHIZAR", labelAr: "كامب شيزار", labelEn: "Camp Shizar", labelFr: "Camp Shizar" },
  { governorateKey: "ALEXANDRIA", key: "KARMOOZ", labelAr: "كرموز", labelEn: "Karmooz", labelFr: "Karmooz" },
  { governorateKey: "ALEXANDRIA", key: "MAHTA_ALRAML", labelAr: "محطة الرمل", labelEn: "Mahta Alraml", labelFr: "Mahta Alraml" },
  { governorateKey: "ALEXANDRIA", key: "MINA_EL-BASAL", labelAr: "مينا البصل", labelEn: "Mina El-Basal", labelFr: "Mina El-Basal" },
  { governorateKey: "ALEXANDRIA", key: "ASAFRA", labelAr: "العصافرة", labelEn: "Asafra", labelFr: "Asafra" },
  { governorateKey: "ALEXANDRIA", key: "AGAMY", labelAr: "العجمي", labelEn: "Agamy", labelFr: "Agamy" },
  { governorateKey: "ALEXANDRIA", key: "BAKOS", labelAr: "بكوس", labelEn: "Bakos", labelFr: "Bakos" },
  { governorateKey: "ALEXANDRIA", key: "BOULKLY", labelAr: "بولكلي", labelEn: "Boulkly", labelFr: "Boulkly" },
  { governorateKey: "ALEXANDRIA", key: "CLEOPATRA", labelAr: "كليوباترا", labelEn: "Cleopatra", labelFr: "Cleopatra" },
  { governorateKey: "ALEXANDRIA", key: "GLIM", labelAr: "جليم", labelEn: "Glim", labelFr: "Glim" },
  { governorateKey: "ALEXANDRIA", key: "AL_MAMURAH", labelAr: "المعمورة", labelEn: "Al Mamurah", labelFr: "Al Mamurah" },
  { governorateKey: "ALEXANDRIA", key: "AL_MANDARA", labelAr: "المندرة", labelEn: "Al Mandara", labelFr: "Al Mandara" },
  { governorateKey: "ALEXANDRIA", key: "MOHARAM_BEK", labelAr: "محرم بك", labelEn: "Moharam Bek", labelFr: "Moharam Bek" },
  { governorateKey: "ALEXANDRIA", key: "ELSHATBY", labelAr: "الشاطبي", labelEn: "Elshatby", labelFr: "Elshatby" },
  { governorateKey: "ALEXANDRIA", key: "SIDI_GABER", labelAr: "سيدي جابر", labelEn: "Sidi Gaber", labelFr: "Sidi Gaber" },
  { governorateKey: "ALEXANDRIA", key: "NORTH_COASTSAHEL", labelAr: "الساحل الشمالي", labelEn: "North Coast/sahel", labelFr: "North Coast/sahel" },
  { governorateKey: "ALEXANDRIA", key: "ALHADRA", labelAr: "الحضرة", labelEn: "Alhadra", labelFr: "Alhadra" },
  { governorateKey: "ALEXANDRIA", key: "ALATTARIN", labelAr: "العطارين", labelEn: "Alattarin", labelFr: "Alattarin" },
  { governorateKey: "ALEXANDRIA", key: "SIDI_KERIR", labelAr: "سيدي كرير", labelEn: "Sidi Kerir", labelFr: "Sidi Kerir" },
  { governorateKey: "ALEXANDRIA", key: "ELGOMROK", labelAr: "الجمرك", labelEn: "Elgomrok", labelFr: "Elgomrok" },
  { governorateKey: "ALEXANDRIA", key: "AL_MAX", labelAr: "المكس", labelEn: "Al Max", labelFr: "Al Max" },
  { governorateKey: "ALEXANDRIA", key: "MARINA", labelAr: "مارينا", labelEn: "Marina", labelFr: "Marina" },
  { governorateKey: "DAKAHLIA", key: "MANSOURA", labelAr: "المنصورة", labelEn: "Mansoura", labelFr: "Mansoura" },
  { governorateKey: "DAKAHLIA", key: "TALKHA", labelAr: "طلخا", labelEn: "Talkha", labelFr: "Talkha" },
  { governorateKey: "DAKAHLIA", key: "MITT_GHAMR", labelAr: "ميت غمر", labelEn: "Mitt Ghamr", labelFr: "Mitt Ghamr" },
  { governorateKey: "DAKAHLIA", key: "DEKERNES", labelAr: "دكرنس", labelEn: "Dekernes", labelFr: "Dekernes" },
  { governorateKey: "DAKAHLIA", key: "AGA", labelAr: "أجا", labelEn: "Aga", labelFr: "Aga" },
  { governorateKey: "DAKAHLIA", key: "MENIA_EL_NASR", labelAr: "منية النصر", labelEn: "Menia El Nasr", labelFr: "Menia El Nasr" },
  { governorateKey: "DAKAHLIA", key: "SINBILLAWIN", labelAr: "السنبلاوين", labelEn: "Sinbillawin", labelFr: "Sinbillawin" },
  { governorateKey: "DAKAHLIA", key: "EL_KURDI", labelAr: "الكردي", labelEn: "El Kurdi", labelFr: "El Kurdi" },
  { governorateKey: "DAKAHLIA", key: "BANI_UBAID", labelAr: "بني عبيد", labelEn: "Bani Ubaid", labelFr: "Bani Ubaid" },
  { governorateKey: "DAKAHLIA", key: "AL_MANZALA", labelAr: "المنزلة", labelEn: "Al Manzala", labelFr: "Al Manzala" },
  { governorateKey: "DAKAHLIA", key: "ALJAMALIA", labelAr: "الجمالية", labelEn: "aljamalia", labelFr: "aljamalia" },
  { governorateKey: "DAKAHLIA", key: "SHERBIN", labelAr: "شربين", labelEn: "Sherbin", labelFr: "Sherbin" },
  { governorateKey: "DAKAHLIA", key: "MATARIA", labelAr: "المطرية", labelEn: "Mataria", labelFr: "Mataria" },
  { governorateKey: "DAKAHLIA", key: "BELQAS", labelAr: "بلقاس", labelEn: "Belqas", labelFr: "Belqas" },
  { governorateKey: "DAKAHLIA", key: "MEET_SALSIL", labelAr: "ميت سلسيل", labelEn: "Meet Salsil", labelFr: "Meet Salsil" },
  { governorateKey: "DAKAHLIA", key: "GAMASA", labelAr: "جمصة", labelEn: "Gamasa", labelFr: "Gamasa" },
  { governorateKey: "DAKAHLIA", key: "MAHALAT_DAMANA", labelAr: "محلة دمنة", labelEn: "Mahalat Damana", labelFr: "Mahalat Damana" },
  { governorateKey: "DAKAHLIA", key: "NABROH", labelAr: "نبروه", labelEn: "Nabroh", labelFr: "Nabroh" },
  { governorateKey: "RED_SEA", key: "HURGHADA", labelAr: "الغردقة", labelEn: "Hurghada", labelFr: "Hurghada" },
  { governorateKey: "RED_SEA", key: "RAS_GHAREB", labelAr: "رأس غارب", labelEn: "Ras Ghareb", labelFr: "Ras Ghareb" },
  { governorateKey: "RED_SEA", key: "SAFAGA", labelAr: "سفاجا", labelEn: "Safaga", labelFr: "Safaga" },
  { governorateKey: "RED_SEA", key: "EL_QUSIAR", labelAr: "القصير", labelEn: "El Qusiar", labelFr: "El Qusiar" },
  { governorateKey: "RED_SEA", key: "MARSA_ALAM", labelAr: "مرسى علم", labelEn: "Marsa Alam", labelFr: "Marsa Alam" },
  { governorateKey: "RED_SEA", key: "SHALATIN", labelAr: "الشلاتين", labelEn: "Shalatin", labelFr: "Shalatin" },
  { governorateKey: "RED_SEA", key: "HALAIB", labelAr: "حلايب", labelEn: "Halaib", labelFr: "Halaib" },
  { governorateKey: "RED_SEA", key: "ALDAHAR", labelAr: "الدهار", labelEn: "Aldahar", labelFr: "Aldahar" },
  { governorateKey: "BEHEIRA", key: "DAMANHOUR", labelAr: "دمنهور", labelEn: "Damanhour", labelFr: "Damanhour" },
  { governorateKey: "BEHEIRA", key: "KAFR_EL_DAWAR", labelAr: "كفر الدوار", labelEn: "Kafr El Dawar", labelFr: "Kafr El Dawar" },
  { governorateKey: "BEHEIRA", key: "RASHID", labelAr: "رشيد", labelEn: "Rashid", labelFr: "Rashid" },
  { governorateKey: "BEHEIRA", key: "EDCO", labelAr: "إدكو", labelEn: "Edco", labelFr: "Edco" },
  { governorateKey: "BEHEIRA", key: "ABU_AL-MATAMIR", labelAr: "أبو المطامير", labelEn: "Abu al-Matamir", labelFr: "Abu al-Matamir" },
  { governorateKey: "BEHEIRA", key: "ABU_HOMS", labelAr: "أبو حمص", labelEn: "Abu Homs", labelFr: "Abu Homs" },
  { governorateKey: "BEHEIRA", key: "DELENGAT", labelAr: "الدلنجات", labelEn: "Delengat", labelFr: "Delengat" },
  { governorateKey: "BEHEIRA", key: "MAHMOUDIYAH", labelAr: "المحمودية", labelEn: "Mahmoudiyah", labelFr: "Mahmoudiyah" },
  { governorateKey: "BEHEIRA", key: "RAHMANIYAH", labelAr: "الرحمانية", labelEn: "Rahmaniyah", labelFr: "Rahmaniyah" },
  { governorateKey: "BEHEIRA", key: "ITAI_BAROUD", labelAr: "إيتاي البارود", labelEn: "Itai Baroud", labelFr: "Itai Baroud" },
  { governorateKey: "BEHEIRA", key: "HOUSH_EISSA", labelAr: "حوش عيسى", labelEn: "Housh Eissa", labelFr: "Housh Eissa" },
  { governorateKey: "BEHEIRA", key: "SHUBRAKHIT", labelAr: "شبراخيت", labelEn: "Shubrakhit", labelFr: "Shubrakhit" },
  { governorateKey: "BEHEIRA", key: "KOM_HAMADA", labelAr: "كوم حمادة", labelEn: "Kom Hamada", labelFr: "Kom Hamada" },
  { governorateKey: "BEHEIRA", key: "BADR", labelAr: "بدر", labelEn: "Badr", labelFr: "Badr" },
  { governorateKey: "BEHEIRA", key: "WADI_NATRUN", labelAr: "وادي النطرون", labelEn: "Wadi Natrun", labelFr: "Wadi Natrun" },
  { governorateKey: "BEHEIRA", key: "NEW_NUBARIA", labelAr: "النوبارية الجديدة", labelEn: "New Nubaria", labelFr: "New Nubaria" },
  { governorateKey: "BEHEIRA", key: "ALNOUBAREYA", labelAr: "النوبارية", labelEn: "Alnoubareya", labelFr: "Alnoubareya" },
  { governorateKey: "FAYOUM", key: "FAYOUM", labelAr: "الفيوم", labelEn: "Fayoum", labelFr: "Fayoum" },
  { governorateKey: "FAYOUM", key: "FAYOUM_EL_GEDIDA", labelAr: "الفيوم الجديدة", labelEn: "Fayoum El Gedida", labelFr: "Fayoum El Gedida" },
  { governorateKey: "FAYOUM", key: "TAMIYA", labelAr: "طامية", labelEn: "Tamiya", labelFr: "Tamiya" },
  { governorateKey: "FAYOUM", key: "SNORES", labelAr: "سنورس", labelEn: "Snores", labelFr: "Snores" },
  { governorateKey: "FAYOUM", key: "ETSA", labelAr: "إطسا", labelEn: "Etsa", labelFr: "Etsa" },
  { governorateKey: "FAYOUM", key: "EPSCHWAY", labelAr: "إبشواي", labelEn: "Epschway", labelFr: "Epschway" },
  { governorateKey: "FAYOUM", key: "YUSUF_EL_SEDIAQ", labelAr: "يوسف الصديق", labelEn: "Yusuf El Sediaq", labelFr: "Yusuf El Sediaq" },
  { governorateKey: "FAYOUM", key: "HADQA", labelAr: "الحادقة", labelEn: "Hadqa", labelFr: "Hadqa" },
  { governorateKey: "FAYOUM", key: "ATSA", labelAr: "اطسا", labelEn: "Atsa", labelFr: "Atsa" },
  { governorateKey: "FAYOUM", key: "ALGAMAA", labelAr: "الجامعة", labelEn: "Algamaa", labelFr: "Algamaa" },
  { governorateKey: "FAYOUM", key: "SAYALA", labelAr: "السيالة", labelEn: "Sayala", labelFr: "Sayala" },
  { governorateKey: "GHARBIYA", key: "TANTA", labelAr: "طنطا", labelEn: "Tanta", labelFr: "Tanta" },
  { governorateKey: "GHARBIYA", key: "AL_MAHALLA_AL_KOBRA", labelAr: "المحلة الكبرى", labelEn: "Al Mahalla Al Kobra", labelFr: "Al Mahalla Al Kobra" },
  { governorateKey: "GHARBIYA", key: "KAFR_EL_ZAYAT", labelAr: "كفر الزيات", labelEn: "Kafr El Zayat", labelFr: "Kafr El Zayat" },
  { governorateKey: "GHARBIYA", key: "ZEFTA", labelAr: "زفتى", labelEn: "Zefta", labelFr: "Zefta" },
  { governorateKey: "GHARBIYA", key: "EL_SANTA", labelAr: "السنطة", labelEn: "El Santa", labelFr: "El Santa" },
  { governorateKey: "GHARBIYA", key: "QUTOUR", labelAr: "قطور", labelEn: "Qutour", labelFr: "Qutour" },
  { governorateKey: "GHARBIYA", key: "BASION", labelAr: "بسيون", labelEn: "Basion", labelFr: "Basion" },
  { governorateKey: "GHARBIYA", key: "SAMANNOUD", labelAr: "سمنود", labelEn: "Samannoud", labelFr: "Samannoud" },
  { governorateKey: "ISMAILIA", key: "ISMAILIA", labelAr: "الإسماعيلية", labelEn: "Ismailia", labelFr: "Ismailia" },
  { governorateKey: "ISMAILIA", key: "FAYED", labelAr: "فايد", labelEn: "Fayed", labelFr: "Fayed" },
  { governorateKey: "ISMAILIA", key: "QANTARA_SHARQ", labelAr: "القنطرة شرق", labelEn: "Qantara Sharq", labelFr: "Qantara Sharq" },
  { governorateKey: "ISMAILIA", key: "QANTARA_GHARB", labelAr: "القنطرة غرب", labelEn: "Qantara Gharb", labelFr: "Qantara Gharb" },
  { governorateKey: "ISMAILIA", key: "EL_TAL_EL_KABIER", labelAr: "التل الكبير", labelEn: "El Tal El Kabier", labelFr: "El Tal El Kabier" },
  { governorateKey: "ISMAILIA", key: "ABU_SAWIR", labelAr: "أبو صوير", labelEn: "Abu Sawir", labelFr: "Abu Sawir" },
  { governorateKey: "ISMAILIA", key: "KASASIEN_EL_GEDIDA", labelAr: "القصاصين الجديدة", labelEn: "Kasasien El Gedida", labelFr: "Kasasien El Gedida" },
  { governorateKey: "ISMAILIA", key: "NEFESHA", labelAr: "نفيشة", labelEn: "Nefesha", labelFr: "Nefesha" },
  { governorateKey: "ISMAILIA", key: "SHEIKH_ZAYED", labelAr: "الشيخ زايد", labelEn: "Sheikh Zayed", labelFr: "Sheikh Zayed" },
  { governorateKey: "MONUFIA", key: "SHBEEN_EL_KOOM", labelAr: "شبين الكوم", labelEn: "Shbeen El Koom", labelFr: "Shbeen El Koom" },
  { governorateKey: "MONUFIA", key: "SADAT_CITY", labelAr: "مدينة السادات", labelEn: "Sadat City", labelFr: "Sadat City" },
  { governorateKey: "MONUFIA", key: "MENOUF", labelAr: "منوف", labelEn: "Menouf", labelFr: "Menouf" },
  { governorateKey: "MONUFIA", key: "SARS_EL-LAYAN", labelAr: "سرس الليان", labelEn: "Sars El-Layan", labelFr: "Sars El-Layan" },
  { governorateKey: "MONUFIA", key: "ASHMON", labelAr: "أشمون", labelEn: "Ashmon", labelFr: "Ashmon" },
  { governorateKey: "MONUFIA", key: "AL_BAGOR", labelAr: "الباجور", labelEn: "Al Bagor", labelFr: "Al Bagor" },
  { governorateKey: "MONUFIA", key: "QUESNA", labelAr: "قويسنا", labelEn: "Quesna", labelFr: "Quesna" },
  { governorateKey: "MONUFIA", key: "BERKAT_EL_SABA", labelAr: "بركة السبع", labelEn: "Berkat El Saba", labelFr: "Berkat El Saba" },
  { governorateKey: "MONUFIA", key: "TALA", labelAr: "تلا", labelEn: "Tala", labelFr: "Tala" },
  { governorateKey: "MONUFIA", key: "AL_SHOHADA", labelAr: "الشهداء", labelEn: "Al Shohada", labelFr: "Al Shohada" },
  { governorateKey: "MINYA", key: "MINYA", labelAr: "المنيا", labelEn: "Minya", labelFr: "Minya" },
  { governorateKey: "MINYA", key: "MINYA_EL_GEDIDA", labelAr: "المنيا الجديدة", labelEn: "Minya El Gedida", labelFr: "Minya El Gedida" },
  { governorateKey: "MINYA", key: "EL_ADWA", labelAr: "العدوة", labelEn: "El Adwa", labelFr: "El Adwa" },
  { governorateKey: "MINYA", key: "MAGAGHA", labelAr: "مغاغة", labelEn: "Magagha", labelFr: "Magagha" },
  { governorateKey: "MINYA", key: "BANI_MAZAR", labelAr: "بني مزار", labelEn: "Bani Mazar", labelFr: "Bani Mazar" },
  { governorateKey: "MINYA", key: "MATTAY", labelAr: "مطاي", labelEn: "Mattay", labelFr: "Mattay" },
  { governorateKey: "MINYA", key: "SAMALUT", labelAr: "سمالوط", labelEn: "Samalut", labelFr: "Samalut" },
  { governorateKey: "MINYA", key: "MADINAT_EL_FEKRIA", labelAr: "المدينة الفكرية", labelEn: "Madinat El Fekria", labelFr: "Madinat El Fekria" },
  { governorateKey: "MINYA", key: "MELOY", labelAr: "ملوي", labelEn: "Meloy", labelFr: "Meloy" },
  { governorateKey: "MINYA", key: "DEIR_MAWAS", labelAr: "دير مواس", labelEn: "Deir Mawas", labelFr: "Deir Mawas" },
  { governorateKey: "MINYA", key: "ABU_QURQAS", labelAr: "ابو قرقاص", labelEn: "Abu Qurqas", labelFr: "Abu Qurqas" },
  { governorateKey: "MINYA", key: "ARD_SULTAN", labelAr: "ارض سلطان", labelEn: "Ard Sultan", labelFr: "Ard Sultan" },
  { governorateKey: "QALIUBIYA", key: "BANHA", labelAr: "بنها", labelEn: "Banha", labelFr: "Banha" },
  { governorateKey: "QALIUBIYA", key: "QALYUB", labelAr: "قليوب", labelEn: "Qalyub", labelFr: "Qalyub" },
  { governorateKey: "QALIUBIYA", key: "SHUBRA_AL_KHAIMAH", labelAr: "شبرا الخيمة", labelEn: "Shubra Al Khaimah", labelFr: "Shubra Al Khaimah" },
  { governorateKey: "QALIUBIYA", key: "AL_QANATER_CHARITY", labelAr: "القناطر الخيرية", labelEn: "Al Qanater Charity", labelFr: "Al Qanater Charity" },
  { governorateKey: "QALIUBIYA", key: "KHANKA", labelAr: "الخانكة", labelEn: "Khanka", labelFr: "Khanka" },
  { governorateKey: "QALIUBIYA", key: "KAFR_SHUKR", labelAr: "كفر شكر", labelEn: "Kafr Shukr", labelFr: "Kafr Shukr" },
  { governorateKey: "QALIUBIYA", key: "TUKH", labelAr: "طوخ", labelEn: "Tukh", labelFr: "Tukh" },
  { governorateKey: "QALIUBIYA", key: "QAHA", labelAr: "قها", labelEn: "Qaha", labelFr: "Qaha" },
  { governorateKey: "QALIUBIYA", key: "OBOUR", labelAr: "العبور", labelEn: "Obour", labelFr: "Obour" },
  { governorateKey: "QALIUBIYA", key: "KHOSOUS", labelAr: "الخصوص", labelEn: "Khosous", labelFr: "Khosous" },
  { governorateKey: "QALIUBIYA", key: "SHIBIN_AL_QANATER", labelAr: "شبين القناطر", labelEn: "Shibin Al Qanater", labelFr: "Shibin Al Qanater" },
  { governorateKey: "QALIUBIYA", key: "MOSTOROD", labelAr: "مسطرد", labelEn: "Mostorod", labelFr: "Mostorod" },
  { governorateKey: "NEW_VALLEY", key: "EL_KHARGA", labelAr: "الخارجة", labelEn: "El Kharga", labelFr: "El Kharga" },
  { governorateKey: "NEW_VALLEY", key: "PARIS", labelAr: "باريس", labelEn: "Paris", labelFr: "Paris" },
  { governorateKey: "NEW_VALLEY", key: "MOUT", labelAr: "موط", labelEn: "Mout", labelFr: "Mout" },
  { governorateKey: "NEW_VALLEY", key: "FARAFRA", labelAr: "الفرافرة", labelEn: "Farafra", labelFr: "Farafra" },
  { governorateKey: "NEW_VALLEY", key: "BALAT", labelAr: "بلاط", labelEn: "Balat", labelFr: "Balat" },
  { governorateKey: "NEW_VALLEY", key: "DAKHLA", labelAr: "الداخلة", labelEn: "Dakhla", labelFr: "Dakhla" },
  { governorateKey: "SUEZ", key: "SUEZ", labelAr: "السويس", labelEn: "Suez", labelFr: "Suez" },
  { governorateKey: "SUEZ", key: "ALGANAYEN", labelAr: "الجناين", labelEn: "Alganayen", labelFr: "Alganayen" },
  { governorateKey: "SUEZ", key: "ATAQAH", labelAr: "عتاقة", labelEn: "Ataqah", labelFr: "Ataqah" },
  { governorateKey: "SUEZ", key: "AIN_SOKHNA", labelAr: "العين السخنة", labelEn: "Ain Sokhna", labelFr: "Ain Sokhna" },
  { governorateKey: "SUEZ", key: "FAYSAL", labelAr: "فيصل", labelEn: "Faysal", labelFr: "Faysal" },
  { governorateKey: "ASWAN", key: "ASWAN", labelAr: "أسوان", labelEn: "Aswan", labelFr: "Aswan" },
  { governorateKey: "ASWAN", key: "ASWAN_EL_GEDIDA", labelAr: "أسوان الجديدة", labelEn: "Aswan El Gedida", labelFr: "Aswan El Gedida" },
  { governorateKey: "ASWAN", key: "DRAU", labelAr: "دراو", labelEn: "Drau", labelFr: "Drau" },
  { governorateKey: "ASWAN", key: "KOM_OMBO", labelAr: "كوم أمبو", labelEn: "Kom Ombo", labelFr: "Kom Ombo" },
  { governorateKey: "ASWAN", key: "NASR_AL_NUBA", labelAr: "نصر النوبة", labelEn: "Nasr Al Nuba", labelFr: "Nasr Al Nuba" },
  { governorateKey: "ASWAN", key: "KALABSHA", labelAr: "كلابشة", labelEn: "Kalabsha", labelFr: "Kalabsha" },
  { governorateKey: "ASWAN", key: "EDFU", labelAr: "إدفو", labelEn: "Edfu", labelFr: "Edfu" },
  { governorateKey: "ASWAN", key: "AL-RADISIYAH", labelAr: "الرديسية", labelEn: "Al-Radisiyah", labelFr: "Al-Radisiyah" },
  { governorateKey: "ASWAN", key: "AL_BASILIA", labelAr: "البصيلية", labelEn: "Al Basilia", labelFr: "Al Basilia" },
  { governorateKey: "ASWAN", key: "AL_SIBAEIA", labelAr: "السباعية", labelEn: "Al Sibaeia", labelFr: "Al Sibaeia" },
  { governorateKey: "ASWAN", key: "ABO_SIMBL_AL_SIYAHIA", labelAr: "ابوسمبل السياحية", labelEn: "Abo Simbl Al Siyahia", labelFr: "Abo Simbl Al Siyahia" },
  { governorateKey: "ASWAN", key: "MARSA_ALAM", labelAr: "مرسى علم", labelEn: "Marsa Alam", labelFr: "Marsa Alam" },
  { governorateKey: "ASSIUT", key: "ASSIUT", labelAr: "أسيوط", labelEn: "Assiut", labelFr: "Assiut" },
  { governorateKey: "ASSIUT", key: "ASSIUT_EL_GEDIDA", labelAr: "أسيوط الجديدة", labelEn: "Assiut El Gedida", labelFr: "Assiut El Gedida" },
  { governorateKey: "ASSIUT", key: "DAYROUT", labelAr: "ديروط", labelEn: "Dayrout", labelFr: "Dayrout" },
  { governorateKey: "ASSIUT", key: "MANFALUT", labelAr: "منفلوط", labelEn: "Manfalut", labelFr: "Manfalut" },
  { governorateKey: "ASSIUT", key: "QUSIYA", labelAr: "القوصية", labelEn: "Qusiya", labelFr: "Qusiya" },
  { governorateKey: "ASSIUT", key: "ABNOUB", labelAr: "أبنوب", labelEn: "Abnoub", labelFr: "Abnoub" },
  { governorateKey: "ASSIUT", key: "ABU_TIG", labelAr: "أبو تيج", labelEn: "Abu Tig", labelFr: "Abu Tig" },
  { governorateKey: "ASSIUT", key: "EL_GHANAIM", labelAr: "الغنايم", labelEn: "El Ghanaim", labelFr: "El Ghanaim" },
  { governorateKey: "ASSIUT", key: "SAHEL_SELIM", labelAr: "ساحل سليم", labelEn: "Sahel Selim", labelFr: "Sahel Selim" },
  { governorateKey: "ASSIUT", key: "EL_BADARI", labelAr: "البداري", labelEn: "El Badari", labelFr: "El Badari" },
  { governorateKey: "ASSIUT", key: "SIDFA", labelAr: "صدفا", labelEn: "Sidfa", labelFr: "Sidfa" },
  { governorateKey: "BENI_SUEF", key: "BANI_SWEIF", labelAr: "بني سويف", labelEn: "Bani Sweif", labelFr: "Bani Sweif" },
  { governorateKey: "BENI_SUEF", key: "BENI_SUEF_EL_GEDIDA", labelAr: "بني سويف الجديدة", labelEn: "Beni Suef El Gedida", labelFr: "Beni Suef El Gedida" },
  { governorateKey: "BENI_SUEF", key: "AL_WASTA", labelAr: "الواسطى", labelEn: "Al Wasta", labelFr: "Al Wasta" },
  { governorateKey: "BENI_SUEF", key: "NASER", labelAr: "ناصر", labelEn: "Naser", labelFr: "Naser" },
  { governorateKey: "BENI_SUEF", key: "EHNASIA", labelAr: "إهناسيا", labelEn: "Ehnasia", labelFr: "Ehnasia" },
  { governorateKey: "BENI_SUEF", key: "BEBA", labelAr: "ببا", labelEn: "beba", labelFr: "beba" },
  { governorateKey: "BENI_SUEF", key: "FASHN", labelAr: "الفشن", labelEn: "Fashn", labelFr: "Fashn" },
  { governorateKey: "BENI_SUEF", key: "SOMASTA", labelAr: "سمسطا", labelEn: "Somasta", labelFr: "Somasta" },
  { governorateKey: "BENI_SUEF", key: "ALABBASERI", labelAr: "الاباصيرى", labelEn: "Alabbaseri", labelFr: "Alabbaseri" },
  { governorateKey: "BENI_SUEF", key: "MOKBEL", labelAr: "مقبل", labelEn: "Mokbel", labelFr: "Mokbel" },
  { governorateKey: "PORT_SAID", key: "PORSAID", labelAr: "بورسعيد", labelEn: "PorSaid", labelFr: "PorSaid" },
  { governorateKey: "PORT_SAID", key: "PORT_FOUAD", labelAr: "بورفؤاد", labelEn: "Port Fouad", labelFr: "Port Fouad" },
  { governorateKey: "PORT_SAID", key: "ALARAB", labelAr: "العرب", labelEn: "Alarab", labelFr: "Alarab" },
  { governorateKey: "PORT_SAID", key: "ZOHOUR", labelAr: "حى الزهور", labelEn: "Zohour", labelFr: "Zohour" },
  { governorateKey: "PORT_SAID", key: "ALSHARQ", labelAr: "حى الشرق", labelEn: "Alsharq", labelFr: "Alsharq" },
  { governorateKey: "PORT_SAID", key: "ALDAWAHI", labelAr: "حى الضواحى", labelEn: "Aldawahi", labelFr: "Aldawahi" },
  { governorateKey: "PORT_SAID", key: "ALMANAKH", labelAr: "حى المناخ", labelEn: "Almanakh", labelFr: "Almanakh" },
  { governorateKey: "PORT_SAID", key: "MUBARAK", labelAr: "حى مبارك", labelEn: "Mubarak", labelFr: "Mubarak" },
  { governorateKey: "DAMIETTA", key: "DAMIETTA", labelAr: "دمياط", labelEn: "Damietta", labelFr: "Damietta" },
  { governorateKey: "DAMIETTA", key: "NEW_DAMIETTA", labelAr: "دمياط الجديدة", labelEn: "New Damietta", labelFr: "New Damietta" },
  { governorateKey: "DAMIETTA", key: "RAS_EL_BAR", labelAr: "رأس البر", labelEn: "Ras El Bar", labelFr: "Ras El Bar" },
  { governorateKey: "DAMIETTA", key: "FARASKOUR", labelAr: "فارسكور", labelEn: "Faraskour", labelFr: "Faraskour" },
  { governorateKey: "DAMIETTA", key: "ZARQA", labelAr: "الزرقا", labelEn: "Zarqa", labelFr: "Zarqa" },
  { governorateKey: "DAMIETTA", key: "ALSARU", labelAr: "السرو", labelEn: "alsaru", labelFr: "alsaru" },
  { governorateKey: "DAMIETTA", key: "ALRUWDA", labelAr: "الروضة", labelEn: "alruwda", labelFr: "alruwda" },
  { governorateKey: "DAMIETTA", key: "KAFR_EL-BATIKH", labelAr: "كفر البطيخ", labelEn: "Kafr El-Batikh", labelFr: "Kafr El-Batikh" },
  { governorateKey: "DAMIETTA", key: "AZBET_AL_BURG", labelAr: "عزبة البرج", labelEn: "Azbet Al Burg", labelFr: "Azbet Al Burg" },
  { governorateKey: "DAMIETTA", key: "MEET_ABOU_GHALIB", labelAr: "ميت أبو غالب", labelEn: "Meet Abou Ghalib", labelFr: "Meet Abou Ghalib" },
  { governorateKey: "DAMIETTA", key: "KAFR_SAAD", labelAr: "كفر سعد", labelEn: "Kafr Saad", labelFr: "Kafr Saad" },
  { governorateKey: "SHARKIA", key: "ZAGAZIG", labelAr: "الزقازيق", labelEn: "Zagazig", labelFr: "Zagazig" },
  { governorateKey: "SHARKIA", key: "AL_ASHR_MEN_RAMADAN", labelAr: "العاشر من رمضان", labelEn: "Al Ashr Men Ramadan", labelFr: "Al Ashr Men Ramadan" },
  { governorateKey: "SHARKIA", key: "MINYA_AL_QAMH", labelAr: "منيا القمح", labelEn: "Minya Al Qamh", labelFr: "Minya Al Qamh" },
  { governorateKey: "SHARKIA", key: "BELBEIS", labelAr: "بلبيس", labelEn: "Belbeis", labelFr: "Belbeis" },
  { governorateKey: "SHARKIA", key: "MASHTOUL_EL_SOUQ", labelAr: "مشتول السوق", labelEn: "Mashtoul El Souq", labelFr: "Mashtoul El Souq" },
  { governorateKey: "SHARKIA", key: "QENAIAT", labelAr: "القنايات", labelEn: "Qenaiat", labelFr: "Qenaiat" },
  { governorateKey: "SHARKIA", key: "ABU_HAMMAD", labelAr: "أبو حماد", labelEn: "Abu Hammad", labelFr: "Abu Hammad" },
  { governorateKey: "SHARKIA", key: "EL_QURAIN", labelAr: "القرين", labelEn: "El Qurain", labelFr: "El Qurain" },
  { governorateKey: "SHARKIA", key: "HEHIA", labelAr: "ههيا", labelEn: "Hehia", labelFr: "Hehia" },
  { governorateKey: "SHARKIA", key: "ABU_KABIR", labelAr: "أبو كبير", labelEn: "Abu Kabir", labelFr: "Abu Kabir" },
  { governorateKey: "SHARKIA", key: "FACCUS", labelAr: "فاقوس", labelEn: "Faccus", labelFr: "Faccus" },
  { governorateKey: "SHARKIA", key: "EL_SALIHIA_EL_GEDIDA", labelAr: "الصالحية الجديدة", labelEn: "El Salihia El Gedida", labelFr: "El Salihia El Gedida" },
  { governorateKey: "SHARKIA", key: "AL_IBRAHIMIYAH", labelAr: "الإبراهيمية", labelEn: "Al Ibrahimiyah", labelFr: "Al Ibrahimiyah" },
  { governorateKey: "SHARKIA", key: "DEIRB_NEGM", labelAr: "ديرب نجم", labelEn: "Deirb Negm", labelFr: "Deirb Negm" },
  { governorateKey: "SHARKIA", key: "KAFR_SAQR", labelAr: "كفر صقر", labelEn: "Kafr Saqr", labelFr: "Kafr Saqr" },
  { governorateKey: "SHARKIA", key: "AWLAD_SAQR", labelAr: "أولاد صقر", labelEn: "Awlad Saqr", labelFr: "Awlad Saqr" },
  { governorateKey: "SHARKIA", key: "HUSSEINIYA", labelAr: "الحسينية", labelEn: "Husseiniya", labelFr: "Husseiniya" },
  { governorateKey: "SHARKIA", key: "SAN_ALHAJAR_ALQABLIA", labelAr: "صان الحجر القبلية", labelEn: "san alhajar alqablia", labelFr: "san alhajar alqablia" },
  { governorateKey: "SHARKIA", key: "MANSHAYAT_ABU_OMAR", labelAr: "منشأة أبو عمر", labelEn: "Manshayat Abu Omar", labelFr: "Manshayat Abu Omar" },
  { governorateKey: "SOUTH_SINAI", key: "AL_TOOR", labelAr: "الطور", labelEn: "Al Toor", labelFr: "Al Toor" },
  { governorateKey: "SOUTH_SINAI", key: "SHARM_EL-SHAIKH", labelAr: "شرم الشيخ", labelEn: "Sharm El-Shaikh", labelFr: "Sharm El-Shaikh" },
  { governorateKey: "SOUTH_SINAI", key: "DAHAB", labelAr: "دهب", labelEn: "Dahab", labelFr: "Dahab" },
  { governorateKey: "SOUTH_SINAI", key: "NUWEIBA", labelAr: "نويبع", labelEn: "Nuweiba", labelFr: "Nuweiba" },
  { governorateKey: "SOUTH_SINAI", key: "TABA", labelAr: "طابا", labelEn: "Taba", labelFr: "Taba" },
  { governorateKey: "SOUTH_SINAI", key: "SAINT_CATHERINE", labelAr: "سانت كاترين", labelEn: "Saint Catherine", labelFr: "Saint Catherine" },
  { governorateKey: "SOUTH_SINAI", key: "ABU_REDIS", labelAr: "أبو رديس", labelEn: "Abu Redis", labelFr: "Abu Redis" },
  { governorateKey: "SOUTH_SINAI", key: "ABU_ZENAIMA", labelAr: "أبو زنيمة", labelEn: "Abu Zenaima", labelFr: "Abu Zenaima" },
  { governorateKey: "SOUTH_SINAI", key: "RAS_SIDR", labelAr: "رأس سدر", labelEn: "Ras Sidr", labelFr: "Ras Sidr" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "KAFR_EL_SHEIKH", labelAr: "كفر الشيخ", labelEn: "Kafr El Sheikh", labelFr: "Kafr El Sheikh" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "KAFR_EL_SHEIKH_DOWNTOWN", labelAr: "وسط البلد كفر الشيخ", labelEn: "Kafr El Sheikh Downtown", labelFr: "Kafr El Sheikh Downtown" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "DESOUQ", labelAr: "دسوق", labelEn: "Desouq", labelFr: "Desouq" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "FOOH", labelAr: "فوه", labelEn: "Fooh", labelFr: "Fooh" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "METOBAS", labelAr: "مطوبس", labelEn: "Metobas", labelFr: "Metobas" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "BURG_AL_BURULLUS", labelAr: "برج البرلس", labelEn: "Burg Al Burullus", labelFr: "Burg Al Burullus" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "BALTIM", labelAr: "بلطيم", labelEn: "Baltim", labelFr: "Baltim" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "MASIEF_BALTIM", labelAr: "مصيف بلطيم", labelEn: "Masief Baltim", labelFr: "Masief Baltim" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "HAMOL", labelAr: "الحامول", labelEn: "Hamol", labelFr: "Hamol" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "BELLA", labelAr: "بيلا", labelEn: "Bella", labelFr: "Bella" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "RIYADH", labelAr: "الرياض", labelEn: "Riyadh", labelFr: "Riyadh" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "SIDI_SALM", labelAr: "سيدي سالم", labelEn: "Sidi Salm", labelFr: "Sidi Salm" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "QELLEN", labelAr: "قلين", labelEn: "Qellen", labelFr: "Qellen" },
  { governorateKey: "KAFR_EL_SHEIKH", key: "SIDI_GHAZI", labelAr: "سيدي غازي", labelEn: "Sidi Ghazi", labelFr: "Sidi Ghazi" },
  { governorateKey: "MATROUH", key: "MARSA_MATROUH", labelAr: "مرسى مطروح", labelEn: "Marsa Matrouh", labelFr: "Marsa Matrouh" },
  { governorateKey: "MATROUH", key: "EL_HAMAM", labelAr: "الحمام", labelEn: "El Hamam", labelFr: "El Hamam" },
  { governorateKey: "MATROUH", key: "ALAMEIN", labelAr: "العلمين", labelEn: "Alamein", labelFr: "Alamein" },
  { governorateKey: "MATROUH", key: "DABAA", labelAr: "الضبعة", labelEn: "Dabaa", labelFr: "Dabaa" },
  { governorateKey: "MATROUH", key: "AL-NAGILA", labelAr: "النجيلة", labelEn: "Al-Nagila", labelFr: "Al-Nagila" },
  { governorateKey: "MATROUH", key: "SIDI_BRANI", labelAr: "سيدي براني", labelEn: "Sidi Brani", labelFr: "Sidi Brani" },
  { governorateKey: "MATROUH", key: "SALLOUM", labelAr: "السلوم", labelEn: "Salloum", labelFr: "Salloum" },
  { governorateKey: "MATROUH", key: "SIWA", labelAr: "سيوة", labelEn: "Siwa", labelFr: "Siwa" },
  { governorateKey: "MATROUH", key: "MARINA", labelAr: "مارينا", labelEn: "Marina", labelFr: "Marina" },
  { governorateKey: "MATROUH", key: "NORTH_COAST", labelAr: "الساحل الشمالى", labelEn: "North Coast", labelFr: "North Coast" },
  { governorateKey: "LUXOR", key: "LUXOR", labelAr: "الأقصر", labelEn: "Luxor", labelFr: "Luxor" },
  { governorateKey: "LUXOR", key: "NEW_LUXOR", labelAr: "الأقصر الجديدة", labelEn: "New Luxor", labelFr: "New Luxor" },
  { governorateKey: "LUXOR", key: "ESNA", labelAr: "إسنا", labelEn: "Esna", labelFr: "Esna" },
  { governorateKey: "LUXOR", key: "NEW_TIBA", labelAr: "طيبة الجديدة", labelEn: "New Tiba", labelFr: "New Tiba" },
  { governorateKey: "LUXOR", key: "AL_ZIYNIA", labelAr: "الزينية", labelEn: "Al ziynia", labelFr: "Al ziynia" },
  { governorateKey: "LUXOR", key: "AL_BAYADIEH", labelAr: "البياضية", labelEn: "Al Bayadieh", labelFr: "Al Bayadieh" },
  { governorateKey: "LUXOR", key: "AL_QARNA", labelAr: "القرنة", labelEn: "Al Qarna", labelFr: "Al Qarna" },
  { governorateKey: "LUXOR", key: "ARMANT", labelAr: "أرمنت", labelEn: "Armant", labelFr: "Armant" },
  { governorateKey: "LUXOR", key: "AL_TUD", labelAr: "الطود", labelEn: "Al Tud", labelFr: "Al Tud" },
  { governorateKey: "QENA", key: "QENA", labelAr: "قنا", labelEn: "Qena", labelFr: "Qena" },
  { governorateKey: "QENA", key: "NEW_QENA", labelAr: "قنا الجديدة", labelEn: "New Qena", labelFr: "New Qena" },
  { governorateKey: "QENA", key: "ABU_TESHT", labelAr: "ابو طشت", labelEn: "Abu Tesht", labelFr: "Abu Tesht" },
  { governorateKey: "QENA", key: "NAG_HAMMADI", labelAr: "نجع حمادي", labelEn: "Nag Hammadi", labelFr: "Nag Hammadi" },
  { governorateKey: "QENA", key: "DESHNA", labelAr: "دشنا", labelEn: "Deshna", labelFr: "Deshna" },
  { governorateKey: "QENA", key: "ALWAQF", labelAr: "الوقف", labelEn: "Alwaqf", labelFr: "Alwaqf" },
  { governorateKey: "QENA", key: "QAFT", labelAr: "قفط", labelEn: "Qaft", labelFr: "Qaft" },
  { governorateKey: "QENA", key: "NAQADA", labelAr: "نقادة", labelEn: "Naqada", labelFr: "Naqada" },
  { governorateKey: "QENA", key: "FARSHOUT", labelAr: "فرشوط", labelEn: "Farshout", labelFr: "Farshout" },
  { governorateKey: "QENA", key: "QUOS", labelAr: "قوص", labelEn: "Quos", labelFr: "Quos" },
  { governorateKey: "NORTH_SINAI", key: "ARISH", labelAr: "العريش", labelEn: "Arish", labelFr: "Arish" },
  { governorateKey: "NORTH_SINAI", key: "SHEIKH_ZOWAID", labelAr: "الشيخ زويد", labelEn: "Sheikh Zowaid", labelFr: "Sheikh Zowaid" },
  { governorateKey: "NORTH_SINAI", key: "NAKHL", labelAr: "نخل", labelEn: "Nakhl", labelFr: "Nakhl" },
  { governorateKey: "NORTH_SINAI", key: "RAFAH", labelAr: "رفح", labelEn: "Rafah", labelFr: "Rafah" },
  { governorateKey: "NORTH_SINAI", key: "BIR_AL-ABED", labelAr: "بئر العبد", labelEn: "Bir al-Abed", labelFr: "Bir al-Abed" },
  { governorateKey: "NORTH_SINAI", key: "AL_HASANA", labelAr: "الحسنة", labelEn: "Al Hasana", labelFr: "Al Hasana" },
  { governorateKey: "SOHAG", key: "SOHAG", labelAr: "سوهاج", labelEn: "Sohag", labelFr: "Sohag" },
  { governorateKey: "SOHAG", key: "SOHAG_EL_GEDIDA", labelAr: "سوهاج الجديدة", labelEn: "Sohag El Gedida", labelFr: "Sohag El Gedida" },
  { governorateKey: "SOHAG", key: "AKHMEEM", labelAr: "أخميم", labelEn: "Akhmeem", labelFr: "Akhmeem" },
  { governorateKey: "SOHAG", key: "AKHMIM_EL_GEDIDA", labelAr: "أخميم الجديدة", labelEn: "Akhmim El Gedida", labelFr: "Akhmim El Gedida" },
  { governorateKey: "SOHAG", key: "ALBALINA", labelAr: "البلينا", labelEn: "Albalina", labelFr: "Albalina" },
  { governorateKey: "SOHAG", key: "EL_MARAGHA", labelAr: "المراغة", labelEn: "El Maragha", labelFr: "El Maragha" },
  { governorateKey: "SOHAG", key: "DAR_AISALAAM", labelAr: "دار السلام", labelEn: "Dar AISalaam", labelFr: "Dar AISalaam" },
  { governorateKey: "SOHAG", key: "GERGA", labelAr: "جرجا", labelEn: "Gerga", labelFr: "Gerga" },
  { governorateKey: "SOHAG", key: "JAHINA_AL_GHARBIA", labelAr: "جهينة الغربية", labelEn: "Jahina Al Gharbia", labelFr: "Jahina Al Gharbia" },
  { governorateKey: "SOHAG", key: "SAQILATUH", labelAr: "ساقلته", labelEn: "Saqilatuh", labelFr: "Saqilatuh" },
  { governorateKey: "SOHAG", key: "TAMA", labelAr: "طما", labelEn: "Tama", labelFr: "Tama" },
  { governorateKey: "SOHAG", key: "TAHTA", labelAr: "طهطا", labelEn: "Tahta", labelFr: "Tahta" },
  { governorateKey: "SOHAG", key: "ALKAWTHAR", labelAr: "الكوثر", labelEn: "Alkawthar", labelFr: "Alkawthar" },
];
