ALTER TABLE "Client"
  ADD COLUMN IF NOT EXISTS "city" TEXT;

CREATE TABLE IF NOT EXISTS "GovernorateLookup" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "key" TEXT NOT NULL,
  "labelAr" TEXT NOT NULL,
  "labelEn" TEXT NOT NULL,
  "labelFr" TEXT NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "GovernorateLookup_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "GovernorateLookup_key_key"
  ON "GovernorateLookup"("key");

CREATE INDEX IF NOT EXISTS "GovernorateLookup_isActive_sortOrder_idx"
  ON "GovernorateLookup"("isActive", "sortOrder");

CREATE TABLE IF NOT EXISTS "CityLookup" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "governorateId" UUID NOT NULL,
  "key" TEXT NOT NULL,
  "labelAr" TEXT NOT NULL,
  "labelEn" TEXT NOT NULL,
  "labelFr" TEXT NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CityLookup_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "CityLookup_governorateId_fkey" FOREIGN KEY ("governorateId")
    REFERENCES "GovernorateLookup"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "CityLookup_governorateId_key_key"
  ON "CityLookup"("governorateId", "key");

CREATE INDEX IF NOT EXISTS "CityLookup_governorateId_isActive_sortOrder_idx"
  ON "CityLookup"("governorateId", "isActive", "sortOrder");

-- Seed canonical Egypt governorates and cities for desktop/local bootstrap
WITH governorates(key, "labelAr", "labelEn", "labelFr", "sortOrder") AS (
  VALUES
    ('CAIRO', 'القاهرة', 'Cairo', 'Cairo', 0),
    ('GIZA', 'الجيزة', 'Giza', 'Giza', 1),
    ('ALEXANDRIA', 'الإسكندرية', 'Alexandria', 'Alexandria', 2),
    ('DAKAHLIA', 'الدقهلية', 'Dakahlia', 'Dakahlia', 3),
    ('RED_SEA', 'البحر الأحمر', 'Red Sea', 'Red Sea', 4),
    ('BEHEIRA', 'البحيرة', 'Beheira', 'Beheira', 5),
    ('FAYOUM', 'الفيوم', 'Fayoum', 'Fayoum', 6),
    ('GHARBIYA', 'الغربية', 'Gharbiya', 'Gharbiya', 7),
    ('ISMAILIA', 'الإسماعيلية', 'Ismailia', 'Ismailia', 8),
    ('MONUFIA', 'المنوفية', 'Monufia', 'Monufia', 9),
    ('MINYA', 'المنيا', 'Minya', 'Minya', 10),
    ('QALIUBIYA', 'القليوبية', 'Qaliubiya', 'Qaliubiya', 11),
    ('NEW_VALLEY', 'الوادي الجديد', 'New Valley', 'New Valley', 12),
    ('SUEZ', 'السويس', 'Suez', 'Suez', 13),
    ('ASWAN', 'أسوان', 'Aswan', 'Aswan', 14),
    ('ASSIUT', 'أسيوط', 'Assiut', 'Assiut', 15),
    ('BENI_SUEF', 'بني سويف', 'Beni Suef', 'Beni Suef', 16),
    ('PORT_SAID', 'بورسعيد', 'Port Said', 'Port Said', 17),
    ('DAMIETTA', 'دمياط', 'Damietta', 'Damietta', 18),
    ('SHARKIA', 'الشرقية', 'Sharkia', 'Sharkia', 19),
    ('SOUTH_SINAI', 'جنوب سيناء', 'South Sinai', 'South Sinai', 20),
    ('KAFR_EL_SHEIKH', 'كفر الشيخ', 'Kafr El Sheikh', 'Kafr El Sheikh', 21),
    ('MATROUH', 'مطروح', 'Matrouh', 'Matrouh', 22),
    ('LUXOR', 'الأقصر', 'Luxor', 'Luxor', 23),
    ('QENA', 'قنا', 'Qena', 'Qena', 24),
    ('NORTH_SINAI', 'شمال سيناء', 'North Sinai', 'North Sinai', 25),
    ('SOHAG', 'سوهاج', 'Sohag', 'Sohag', 26)
)
INSERT INTO "GovernorateLookup" ("key", "labelAr", "labelEn", "labelFr", "isActive", "sortOrder")
SELECT key, "labelAr", "labelEn", "labelFr", true, "sortOrder" FROM governorates
ON CONFLICT ("key") DO UPDATE
SET "labelAr" = EXCLUDED."labelAr",
    "labelEn" = EXCLUDED."labelEn",
    "labelFr" = EXCLUDED."labelFr",
    "isActive" = true,
    "sortOrder" = EXCLUDED."sortOrder",
    "updatedAt" = CURRENT_TIMESTAMP;

WITH cities("governorateKey", "key", "labelAr", "labelEn", "labelFr", "sortOrder") AS (
  VALUES
    ('CAIRO', '15_MAY', '15 مايو', '15 May', '15 May', 0),
    ('CAIRO', 'AL_AZBAKEYAH', 'الازبكية', 'Al Azbakeyah', 'Al Azbakeyah', 1),
    ('CAIRO', 'AL_BASATIN', 'البساتين', 'Al Basatin', 'Al Basatin', 2),
    ('CAIRO', 'TEBIN', 'التبين', 'Tebin', 'Tebin', 3),
    ('CAIRO', 'EL-KHALIFA', 'الخليفة', 'El-Khalifa', 'El-Khalifa', 4),
    ('CAIRO', 'EL_DARRASA', 'الدراسة', 'El darrasa', 'El darrasa', 5),
    ('CAIRO', 'ALDARB_ALAHMAR', 'الدرب الاحمر', 'Aldarb Alahmar', 'Aldarb Alahmar', 6),
    ('CAIRO', 'ZAWYA_AL-HAMRA', 'الزاوية الحمراء', 'Zawya al-Hamra', 'Zawya al-Hamra', 7),
    ('CAIRO', 'EL-ZAYTOUN', 'الزيتون', 'El-Zaytoun', 'El-Zaytoun', 8),
    ('CAIRO', 'SAHEL', 'الساحل', 'Sahel', 'Sahel', 9),
    ('CAIRO', 'EL_SALAM', 'السلام', 'El Salam', 'El Salam', 10),
    ('CAIRO', 'SAYEDA_ZEINAB', 'السيدة زينب', 'Sayeda Zeinab', 'Sayeda Zeinab', 11),
    ('CAIRO', 'EL_SHARABEYA', 'الشرابية', 'El Sharabeya', 'El Sharabeya', 12),
    ('CAIRO', 'SHOROUK', 'مدينة الشروق', 'Shorouk', 'Shorouk', 13),
    ('CAIRO', 'EL_DAHER', 'الظاهر', 'El Daher', 'El Daher', 14),
    ('CAIRO', 'ATABA', 'العتبة', 'Ataba', 'Ataba', 15),
    ('CAIRO', 'NEW_CAIRO', 'القاهرة الجديدة', 'New Cairo', 'New Cairo', 16),
    ('CAIRO', 'EL_MARG', 'المرج', 'El Marg', 'El Marg', 17),
    ('CAIRO', 'EZBET_EL_NAKHL', 'عزبة النخل', 'Ezbet el Nakhl', 'Ezbet el Nakhl', 18),
    ('CAIRO', 'MATAREYA', 'المطرية', 'Matareya', 'Matareya', 19),
    ('CAIRO', 'MAADI', 'المعادى', 'Maadi', 'Maadi', 20),
    ('CAIRO', 'MAASARA', 'المعصرة', 'Maasara', 'Maasara', 21),
    ('CAIRO', 'MOKATTAM', 'المقطم', 'Mokattam', 'Mokattam', 22),
    ('CAIRO', 'MANYAL', 'المنيل', 'Manyal', 'Manyal', 23),
    ('CAIRO', 'MOSKY', 'الموسكى', 'Mosky', 'Mosky', 24),
    ('CAIRO', 'NOZHA', 'النزهة', 'Nozha', 'Nozha', 25),
    ('CAIRO', 'WAILY', 'الوايلى', 'Waily', 'Waily', 26),
    ('CAIRO', 'BAB_AL-SHEREIA', 'باب الشعرية', 'Bab al-Shereia', 'Bab al-Shereia', 27),
    ('CAIRO', 'BOLAQ', 'بولاق', 'Bolaq', 'Bolaq', 28),
    ('CAIRO', 'GARDEN_CITY', 'جاردن سيتى', 'Garden City', 'Garden City', 29),
    ('CAIRO', 'HADAYEK_EL-KOBBA', 'حدائق القبة', 'Hadayek El-Kobba', 'Hadayek El-Kobba', 30),
    ('CAIRO', 'HELWAN', 'حلوان', 'Helwan', 'Helwan', 31),
    ('CAIRO', 'DAR_AL_SALAM', 'دار السلام', 'Dar Al Salam', 'Dar Al Salam', 32),
    ('CAIRO', 'SHUBRA', 'شبرا', 'Shubra', 'Shubra', 33),
    ('CAIRO', 'TURA', 'طره', 'Tura', 'Tura', 34),
    ('CAIRO', 'ABDEEN', 'عابدين', 'Abdeen', 'Abdeen', 35),
    ('CAIRO', 'ABASEYA', 'عباسية', 'Abaseya', 'Abaseya', 36),
    ('CAIRO', 'AIN_SHAMS', 'عين شمس', 'Ain Shams', 'Ain Shams', 37),
    ('CAIRO', 'NASR_CITY', 'مدينة نصر', 'Nasr City', 'Nasr City', 38),
    ('CAIRO', 'NEW_HELIOPOLIS', 'مصر الجديدة', 'New Heliopolis', 'New Heliopolis', 39),
    ('CAIRO', 'MASR_AL_QADIMA', 'مصر القديمة', 'Masr Al Qadima', 'Masr Al Qadima', 40),
    ('CAIRO', 'MANSHEYA_NASIR', 'منشية ناصر', 'Mansheya Nasir', 'Mansheya Nasir', 41),
    ('CAIRO', 'BADR_CITY', 'مدينة بدر', 'Badr City', 'Badr City', 42),
    ('CAIRO', 'OBOUR_CITY', 'مدينة العبور', 'Obour City', 'Obour City', 43),
    ('CAIRO', 'CAIRO_DOWNTOWN', 'وسط البلد', 'Cairo Downtown', 'Cairo Downtown', 44),
    ('CAIRO', 'ZAMALEK', 'الزمالك', 'Zamalek', 'Zamalek', 45),
    ('CAIRO', 'KASR_EL_NILE', 'قصر النيل', 'Kasr El Nile', 'Kasr El Nile', 46),
    ('CAIRO', 'REHAB', 'الرحاب', 'Rehab', 'Rehab', 47),
    ('CAIRO', 'KATAMEYA', 'القطامية', 'Katameya', 'Katameya', 48),
    ('CAIRO', 'MADINTY', 'مدينتي', 'Madinty', 'Madinty', 49),
    ('CAIRO', 'ROD_ALFARAG', 'روض الفرج', 'Rod Alfarag', 'Rod Alfarag', 50),
    ('CAIRO', 'SHERATON', 'شيراتون', 'Sheraton', 'Sheraton', 51),
    ('CAIRO', 'EL-GAMALEYA', 'الجمالية', 'El-Gamaleya', 'El-Gamaleya', 52),
    ('CAIRO', '10TH_OF_RAMADAN_CITY', 'العاشر من رمضان', '10th of Ramadan City', '10th of Ramadan City', 53),
    ('CAIRO', 'HELMEYAT_ALZAYTOUN', 'الحلمية', 'Helmeyat Alzaytoun', 'Helmeyat Alzaytoun', 54),
    ('CAIRO', 'NEW_NOZHA', 'النزهة الجديدة', 'New Nozha', 'New Nozha', 55),
    ('CAIRO', 'CAPITAL_NEW', 'العاصمة الإدارية', 'Capital New', 'Capital New', 56),
    ('GIZA', 'GIZA', 'الجيزة', 'Giza', 'Giza', 57),
    ('GIZA', 'SIXTH_OF_OCTOBER', 'السادس من أكتوبر', 'Sixth of October', 'Sixth of October', 58),
    ('GIZA', 'SHEIKH_ZAYED', 'الشيخ زايد', 'Sheikh Zayed', 'Sheikh Zayed', 59),
    ('GIZA', 'HAWAMDIYAH', 'الحوامدية', 'Hawamdiyah', 'Hawamdiyah', 60),
    ('GIZA', 'AL_BADRASHEEN', 'البدرشين', 'Al Badrasheen', 'Al Badrasheen', 61),
    ('GIZA', 'SAF', 'الصف', 'Saf', 'Saf', 62),
    ('GIZA', 'ATFIH', 'أطفيح', 'Atfih', 'Atfih', 63),
    ('GIZA', 'AL_AYAT', 'العياط', 'Al Ayat', 'Al Ayat', 64),
    ('GIZA', 'AL-BAWAITI', 'الباويطي', 'Al-Bawaiti', 'Al-Bawaiti', 65),
    ('GIZA', 'MANSHIYETAL_QANATER', 'منشأة القناطر', 'ManshiyetAl Qanater', 'ManshiyetAl Qanater', 66),
    ('GIZA', 'OASEEM', 'أوسيم', 'Oaseem', 'Oaseem', 67),
    ('GIZA', 'KERDASA', 'كرداسة', 'Kerdasa', 'Kerdasa', 68),
    ('GIZA', 'ABU_NOMROS', 'أبو النمرس', 'Abu Nomros', 'Abu Nomros', 69),
    ('GIZA', 'KAFR_GHATI', 'كفر غطاطي', 'Kafr Ghati', 'Kafr Ghati', 70),
    ('GIZA', 'MANSHIYET_AL_BAKARI', 'منشأة البكاري', 'Manshiyet Al Bakari', 'Manshiyet Al Bakari', 71),
    ('GIZA', 'DOKKI', 'الدقى', 'Dokki', 'Dokki', 72),
    ('GIZA', 'AGOUZA', 'العجوزة', 'Agouza', 'Agouza', 73),
    ('GIZA', 'HARAM', 'الهرم', 'Haram', 'Haram', 74),
    ('GIZA', 'WARRAQ', 'الوراق', 'Warraq', 'Warraq', 75),
    ('GIZA', 'IMBABA', 'امبابة', 'Imbaba', 'Imbaba', 76),
    ('GIZA', 'BOULAQ_DAKROUR', 'بولاق الدكرور', 'Boulaq Dakrour', 'Boulaq Dakrour', 77),
    ('GIZA', 'AL_WAHAT_AL_BAHARIA', 'الواحات البحرية', 'Al Wahat Al Baharia', 'Al Wahat Al Baharia', 78),
    ('GIZA', 'OMRANEYA', 'العمرانية', 'Omraneya', 'Omraneya', 79),
    ('GIZA', 'MONEEB', 'المنيب', 'Moneeb', 'Moneeb', 80),
    ('GIZA', 'BIN_ALSARAYAT', 'بين السرايات', 'Bin Alsarayat', 'Bin Alsarayat', 81),
    ('GIZA', 'KIT_KAT', 'الكيت كات', 'Kit Kat', 'Kit Kat', 82),
    ('GIZA', 'MOHANDESSIN', 'المهندسين', 'Mohandessin', 'Mohandessin', 83),
    ('GIZA', 'FAISAL', 'فيصل', 'Faisal', 'Faisal', 84),
    ('GIZA', 'ABU_RAWASH', 'أبو رواش', 'Abu Rawash', 'Abu Rawash', 85),
    ('GIZA', 'HADAYEK_ALAHRAM', 'حدائق الأهرام', 'Hadayek Alahram', 'Hadayek Alahram', 86),
    ('GIZA', 'HARANEYA', 'الحرانية', 'Haraneya', 'Haraneya', 87),
    ('GIZA', 'HADAYEK_OCTOBER', 'حدائق اكتوبر', 'Hadayek October', 'Hadayek October', 88),
    ('GIZA', 'SAFT_ALLABAN', 'صفط اللبن', 'Saft Allaban', 'Saft Allaban', 89),
    ('GIZA', 'SMART_VILLAGE', 'القرية الذكية', 'Smart Village', 'Smart Village', 90),
    ('GIZA', 'ARD_ELLWAA', 'ارض اللواء', 'Ard Ellwaa', 'Ard Ellwaa', 91),
    ('ALEXANDRIA', 'ABU_QIR', 'ابو قير', 'Abu Qir', 'Abu Qir', 92),
    ('ALEXANDRIA', 'AL_IBRAHIMEYAH', 'الابراهيمية', 'Al Ibrahimeyah', 'Al Ibrahimeyah', 93),
    ('ALEXANDRIA', 'AZARITA', 'الأزاريطة', 'Azarita', 'Azarita', 94),
    ('ALEXANDRIA', 'ANFOUSHI', 'الانفوشى', 'Anfoushi', 'Anfoushi', 95),
    ('ALEXANDRIA', 'DEKHEILA', 'الدخيلة', 'Dekheila', 'Dekheila', 96),
    ('ALEXANDRIA', 'EL_SOYOF', 'السيوف', 'El Soyof', 'El Soyof', 97),
    ('ALEXANDRIA', 'AMERIA', 'العامرية', 'Ameria', 'Ameria', 98),
    ('ALEXANDRIA', 'EL_LABBAN', 'اللبان', 'El Labban', 'El Labban', 99),
    ('ALEXANDRIA', 'AL_MAFROUZA', 'المفروزة', 'Al Mafrouza', 'Al Mafrouza', 100),
    ('ALEXANDRIA', 'EL_MONTAZA', 'المنتزه', 'El Montaza', 'El Montaza', 101),
    ('ALEXANDRIA', 'MANSHEYA', 'المنشية', 'Mansheya', 'Mansheya', 102),
    ('ALEXANDRIA', 'NASERIA', 'الناصرية', 'Naseria', 'Naseria', 103),
    ('ALEXANDRIA', 'AMBROZO', 'امبروزو', 'Ambrozo', 'Ambrozo', 104),
    ('ALEXANDRIA', 'BAB_SHARQ', 'باب شرق', 'Bab Sharq', 'Bab Sharq', 105),
    ('ALEXANDRIA', 'BOURJ_ALARAB', 'برج العرب', 'Bourj Alarab', 'Bourj Alarab', 106),
    ('ALEXANDRIA', 'STANLEY', 'ستانلى', 'Stanley', 'Stanley', 107),
    ('ALEXANDRIA', 'SMOUHA', 'سموحة', 'Smouha', 'Smouha', 108),
    ('ALEXANDRIA', 'SIDI_BISHR', 'سيدى بشر', 'Sidi Bishr', 'Sidi Bishr', 109),
    ('ALEXANDRIA', 'SHADS', 'شدس', 'Shads', 'Shads', 110),
    ('ALEXANDRIA', 'GHEET_ALENAB', 'غيط العنب', 'Gheet Alenab', 'Gheet Alenab', 111),
    ('ALEXANDRIA', 'FLEMING', 'فلمينج', 'Fleming', 'Fleming', 112),
    ('ALEXANDRIA', 'VICTORIA', 'فيكتوريا', 'Victoria', 'Victoria', 113),
    ('ALEXANDRIA', 'CAMP_SHIZAR', 'كامب شيزار', 'Camp Shizar', 'Camp Shizar', 114),
    ('ALEXANDRIA', 'KARMOOZ', 'كرموز', 'Karmooz', 'Karmooz', 115),
    ('ALEXANDRIA', 'MAHTA_ALRAML', 'محطة الرمل', 'Mahta Alraml', 'Mahta Alraml', 116),
    ('ALEXANDRIA', 'MINA_EL-BASAL', 'مينا البصل', 'Mina El-Basal', 'Mina El-Basal', 117),
    ('ALEXANDRIA', 'ASAFRA', 'العصافرة', 'Asafra', 'Asafra', 118),
    ('ALEXANDRIA', 'AGAMY', 'العجمي', 'Agamy', 'Agamy', 119),
    ('ALEXANDRIA', 'BAKOS', 'بكوس', 'Bakos', 'Bakos', 120),
    ('ALEXANDRIA', 'BOULKLY', 'بولكلي', 'Boulkly', 'Boulkly', 121),
    ('ALEXANDRIA', 'CLEOPATRA', 'كليوباترا', 'Cleopatra', 'Cleopatra', 122),
    ('ALEXANDRIA', 'GLIM', 'جليم', 'Glim', 'Glim', 123),
    ('ALEXANDRIA', 'AL_MAMURAH', 'المعمورة', 'Al Mamurah', 'Al Mamurah', 124),
    ('ALEXANDRIA', 'AL_MANDARA', 'المندرة', 'Al Mandara', 'Al Mandara', 125),
    ('ALEXANDRIA', 'MOHARAM_BEK', 'محرم بك', 'Moharam Bek', 'Moharam Bek', 126),
    ('ALEXANDRIA', 'ELSHATBY', 'الشاطبي', 'Elshatby', 'Elshatby', 127),
    ('ALEXANDRIA', 'SIDI_GABER', 'سيدي جابر', 'Sidi Gaber', 'Sidi Gaber', 128),
    ('ALEXANDRIA', 'NORTH_COASTSAHEL', 'الساحل الشمالي', 'North Coast/sahel', 'North Coast/sahel', 129),
    ('ALEXANDRIA', 'ALHADRA', 'الحضرة', 'Alhadra', 'Alhadra', 130),
    ('ALEXANDRIA', 'ALATTARIN', 'العطارين', 'Alattarin', 'Alattarin', 131),
    ('ALEXANDRIA', 'SIDI_KERIR', 'سيدي كرير', 'Sidi Kerir', 'Sidi Kerir', 132),
    ('ALEXANDRIA', 'ELGOMROK', 'الجمرك', 'Elgomrok', 'Elgomrok', 133),
    ('ALEXANDRIA', 'AL_MAX', 'المكس', 'Al Max', 'Al Max', 134),
    ('ALEXANDRIA', 'MARINA', 'مارينا', 'Marina', 'Marina', 135),
    ('DAKAHLIA', 'MANSOURA', 'المنصورة', 'Mansoura', 'Mansoura', 136),
    ('DAKAHLIA', 'TALKHA', 'طلخا', 'Talkha', 'Talkha', 137),
    ('DAKAHLIA', 'MITT_GHAMR', 'ميت غمر', 'Mitt Ghamr', 'Mitt Ghamr', 138),
    ('DAKAHLIA', 'DEKERNES', 'دكرنس', 'Dekernes', 'Dekernes', 139),
    ('DAKAHLIA', 'AGA', 'أجا', 'Aga', 'Aga', 140),
    ('DAKAHLIA', 'MENIA_EL_NASR', 'منية النصر', 'Menia El Nasr', 'Menia El Nasr', 141),
    ('DAKAHLIA', 'SINBILLAWIN', 'السنبلاوين', 'Sinbillawin', 'Sinbillawin', 142),
    ('DAKAHLIA', 'EL_KURDI', 'الكردي', 'El Kurdi', 'El Kurdi', 143),
    ('DAKAHLIA', 'BANI_UBAID', 'بني عبيد', 'Bani Ubaid', 'Bani Ubaid', 144),
    ('DAKAHLIA', 'AL_MANZALA', 'المنزلة', 'Al Manzala', 'Al Manzala', 145),
    ('DAKAHLIA', 'ALJAMALIA', 'الجمالية', 'aljamalia', 'aljamalia', 146),
    ('DAKAHLIA', 'SHERBIN', 'شربين', 'Sherbin', 'Sherbin', 147),
    ('DAKAHLIA', 'MATARIA', 'المطرية', 'Mataria', 'Mataria', 148),
    ('DAKAHLIA', 'BELQAS', 'بلقاس', 'Belqas', 'Belqas', 149),
    ('DAKAHLIA', 'MEET_SALSIL', 'ميت سلسيل', 'Meet Salsil', 'Meet Salsil', 150),
    ('DAKAHLIA', 'GAMASA', 'جمصة', 'Gamasa', 'Gamasa', 151),
    ('DAKAHLIA', 'MAHALAT_DAMANA', 'محلة دمنة', 'Mahalat Damana', 'Mahalat Damana', 152),
    ('DAKAHLIA', 'NABROH', 'نبروه', 'Nabroh', 'Nabroh', 153),
    ('RED_SEA', 'HURGHADA', 'الغردقة', 'Hurghada', 'Hurghada', 154),
    ('RED_SEA', 'RAS_GHAREB', 'رأس غارب', 'Ras Ghareb', 'Ras Ghareb', 155),
    ('RED_SEA', 'SAFAGA', 'سفاجا', 'Safaga', 'Safaga', 156),
    ('RED_SEA', 'EL_QUSIAR', 'القصير', 'El Qusiar', 'El Qusiar', 157),
    ('RED_SEA', 'MARSA_ALAM', 'مرسى علم', 'Marsa Alam', 'Marsa Alam', 158),
    ('RED_SEA', 'SHALATIN', 'الشلاتين', 'Shalatin', 'Shalatin', 159),
    ('RED_SEA', 'HALAIB', 'حلايب', 'Halaib', 'Halaib', 160),
    ('RED_SEA', 'ALDAHAR', 'الدهار', 'Aldahar', 'Aldahar', 161),
    ('BEHEIRA', 'DAMANHOUR', 'دمنهور', 'Damanhour', 'Damanhour', 162),
    ('BEHEIRA', 'KAFR_EL_DAWAR', 'كفر الدوار', 'Kafr El Dawar', 'Kafr El Dawar', 163),
    ('BEHEIRA', 'RASHID', 'رشيد', 'Rashid', 'Rashid', 164),
    ('BEHEIRA', 'EDCO', 'إدكو', 'Edco', 'Edco', 165),
    ('BEHEIRA', 'ABU_AL-MATAMIR', 'أبو المطامير', 'Abu al-Matamir', 'Abu al-Matamir', 166),
    ('BEHEIRA', 'ABU_HOMS', 'أبو حمص', 'Abu Homs', 'Abu Homs', 167),
    ('BEHEIRA', 'DELENGAT', 'الدلنجات', 'Delengat', 'Delengat', 168),
    ('BEHEIRA', 'MAHMOUDIYAH', 'المحمودية', 'Mahmoudiyah', 'Mahmoudiyah', 169),
    ('BEHEIRA', 'RAHMANIYAH', 'الرحمانية', 'Rahmaniyah', 'Rahmaniyah', 170),
    ('BEHEIRA', 'ITAI_BAROUD', 'إيتاي البارود', 'Itai Baroud', 'Itai Baroud', 171),
    ('BEHEIRA', 'HOUSH_EISSA', 'حوش عيسى', 'Housh Eissa', 'Housh Eissa', 172),
    ('BEHEIRA', 'SHUBRAKHIT', 'شبراخيت', 'Shubrakhit', 'Shubrakhit', 173),
    ('BEHEIRA', 'KOM_HAMADA', 'كوم حمادة', 'Kom Hamada', 'Kom Hamada', 174),
    ('BEHEIRA', 'BADR', 'بدر', 'Badr', 'Badr', 175),
    ('BEHEIRA', 'WADI_NATRUN', 'وادي النطرون', 'Wadi Natrun', 'Wadi Natrun', 176),
    ('BEHEIRA', 'NEW_NUBARIA', 'النوبارية الجديدة', 'New Nubaria', 'New Nubaria', 177),
    ('BEHEIRA', 'ALNOUBAREYA', 'النوبارية', 'Alnoubareya', 'Alnoubareya', 178),
    ('FAYOUM', 'FAYOUM', 'الفيوم', 'Fayoum', 'Fayoum', 179),
    ('FAYOUM', 'FAYOUM_EL_GEDIDA', 'الفيوم الجديدة', 'Fayoum El Gedida', 'Fayoum El Gedida', 180),
    ('FAYOUM', 'TAMIYA', 'طامية', 'Tamiya', 'Tamiya', 181),
    ('FAYOUM', 'SNORES', 'سنورس', 'Snores', 'Snores', 182),
    ('FAYOUM', 'ETSA', 'إطسا', 'Etsa', 'Etsa', 183),
    ('FAYOUM', 'EPSCHWAY', 'إبشواي', 'Epschway', 'Epschway', 184),
    ('FAYOUM', 'YUSUF_EL_SEDIAQ', 'يوسف الصديق', 'Yusuf El Sediaq', 'Yusuf El Sediaq', 185),
    ('FAYOUM', 'HADQA', 'الحادقة', 'Hadqa', 'Hadqa', 186),
    ('FAYOUM', 'ATSA', 'اطسا', 'Atsa', 'Atsa', 187),
    ('FAYOUM', 'ALGAMAA', 'الجامعة', 'Algamaa', 'Algamaa', 188),
    ('FAYOUM', 'SAYALA', 'السيالة', 'Sayala', 'Sayala', 189),
    ('GHARBIYA', 'TANTA', 'طنطا', 'Tanta', 'Tanta', 190),
    ('GHARBIYA', 'AL_MAHALLA_AL_KOBRA', 'المحلة الكبرى', 'Al Mahalla Al Kobra', 'Al Mahalla Al Kobra', 191),
    ('GHARBIYA', 'KAFR_EL_ZAYAT', 'كفر الزيات', 'Kafr El Zayat', 'Kafr El Zayat', 192),
    ('GHARBIYA', 'ZEFTA', 'زفتى', 'Zefta', 'Zefta', 193),
    ('GHARBIYA', 'EL_SANTA', 'السنطة', 'El Santa', 'El Santa', 194),
    ('GHARBIYA', 'QUTOUR', 'قطور', 'Qutour', 'Qutour', 195),
    ('GHARBIYA', 'BASION', 'بسيون', 'Basion', 'Basion', 196),
    ('GHARBIYA', 'SAMANNOUD', 'سمنود', 'Samannoud', 'Samannoud', 197),
    ('ISMAILIA', 'ISMAILIA', 'الإسماعيلية', 'Ismailia', 'Ismailia', 198),
    ('ISMAILIA', 'FAYED', 'فايد', 'Fayed', 'Fayed', 199),
    ('ISMAILIA', 'QANTARA_SHARQ', 'القنطرة شرق', 'Qantara Sharq', 'Qantara Sharq', 200),
    ('ISMAILIA', 'QANTARA_GHARB', 'القنطرة غرب', 'Qantara Gharb', 'Qantara Gharb', 201),
    ('ISMAILIA', 'EL_TAL_EL_KABIER', 'التل الكبير', 'El Tal El Kabier', 'El Tal El Kabier', 202),
    ('ISMAILIA', 'ABU_SAWIR', 'أبو صوير', 'Abu Sawir', 'Abu Sawir', 203),
    ('ISMAILIA', 'KASASIEN_EL_GEDIDA', 'القصاصين الجديدة', 'Kasasien El Gedida', 'Kasasien El Gedida', 204),
    ('ISMAILIA', 'NEFESHA', 'نفيشة', 'Nefesha', 'Nefesha', 205),
    ('ISMAILIA', 'SHEIKH_ZAYED', 'الشيخ زايد', 'Sheikh Zayed', 'Sheikh Zayed', 206),
    ('MONUFIA', 'SHBEEN_EL_KOOM', 'شبين الكوم', 'Shbeen El Koom', 'Shbeen El Koom', 207),
    ('MONUFIA', 'SADAT_CITY', 'مدينة السادات', 'Sadat City', 'Sadat City', 208),
    ('MONUFIA', 'MENOUF', 'منوف', 'Menouf', 'Menouf', 209),
    ('MONUFIA', 'SARS_EL-LAYAN', 'سرس الليان', 'Sars El-Layan', 'Sars El-Layan', 210),
    ('MONUFIA', 'ASHMON', 'أشمون', 'Ashmon', 'Ashmon', 211),
    ('MONUFIA', 'AL_BAGOR', 'الباجور', 'Al Bagor', 'Al Bagor', 212),
    ('MONUFIA', 'QUESNA', 'قويسنا', 'Quesna', 'Quesna', 213),
    ('MONUFIA', 'BERKAT_EL_SABA', 'بركة السبع', 'Berkat El Saba', 'Berkat El Saba', 214),
    ('MONUFIA', 'TALA', 'تلا', 'Tala', 'Tala', 215),
    ('MONUFIA', 'AL_SHOHADA', 'الشهداء', 'Al Shohada', 'Al Shohada', 216),
    ('MINYA', 'MINYA', 'المنيا', 'Minya', 'Minya', 217),
    ('MINYA', 'MINYA_EL_GEDIDA', 'المنيا الجديدة', 'Minya El Gedida', 'Minya El Gedida', 218),
    ('MINYA', 'EL_ADWA', 'العدوة', 'El Adwa', 'El Adwa', 219),
    ('MINYA', 'MAGAGHA', 'مغاغة', 'Magagha', 'Magagha', 220),
    ('MINYA', 'BANI_MAZAR', 'بني مزار', 'Bani Mazar', 'Bani Mazar', 221),
    ('MINYA', 'MATTAY', 'مطاي', 'Mattay', 'Mattay', 222),
    ('MINYA', 'SAMALUT', 'سمالوط', 'Samalut', 'Samalut', 223),
    ('MINYA', 'MADINAT_EL_FEKRIA', 'المدينة الفكرية', 'Madinat El Fekria', 'Madinat El Fekria', 224),
    ('MINYA', 'MELOY', 'ملوي', 'Meloy', 'Meloy', 225),
    ('MINYA', 'DEIR_MAWAS', 'دير مواس', 'Deir Mawas', 'Deir Mawas', 226),
    ('MINYA', 'ABU_QURQAS', 'ابو قرقاص', 'Abu Qurqas', 'Abu Qurqas', 227),
    ('MINYA', 'ARD_SULTAN', 'ارض سلطان', 'Ard Sultan', 'Ard Sultan', 228),
    ('QALIUBIYA', 'BANHA', 'بنها', 'Banha', 'Banha', 229),
    ('QALIUBIYA', 'QALYUB', 'قليوب', 'Qalyub', 'Qalyub', 230),
    ('QALIUBIYA', 'SHUBRA_AL_KHAIMAH', 'شبرا الخيمة', 'Shubra Al Khaimah', 'Shubra Al Khaimah', 231),
    ('QALIUBIYA', 'AL_QANATER_CHARITY', 'القناطر الخيرية', 'Al Qanater Charity', 'Al Qanater Charity', 232),
    ('QALIUBIYA', 'KHANKA', 'الخانكة', 'Khanka', 'Khanka', 233),
    ('QALIUBIYA', 'KAFR_SHUKR', 'كفر شكر', 'Kafr Shukr', 'Kafr Shukr', 234),
    ('QALIUBIYA', 'TUKH', 'طوخ', 'Tukh', 'Tukh', 235),
    ('QALIUBIYA', 'QAHA', 'قها', 'Qaha', 'Qaha', 236),
    ('QALIUBIYA', 'OBOUR', 'العبور', 'Obour', 'Obour', 237),
    ('QALIUBIYA', 'KHOSOUS', 'الخصوص', 'Khosous', 'Khosous', 238),
    ('QALIUBIYA', 'SHIBIN_AL_QANATER', 'شبين القناطر', 'Shibin Al Qanater', 'Shibin Al Qanater', 239),
    ('QALIUBIYA', 'MOSTOROD', 'مسطرد', 'Mostorod', 'Mostorod', 240),
    ('NEW_VALLEY', 'EL_KHARGA', 'الخارجة', 'El Kharga', 'El Kharga', 241),
    ('NEW_VALLEY', 'PARIS', 'باريس', 'Paris', 'Paris', 242),
    ('NEW_VALLEY', 'MOUT', 'موط', 'Mout', 'Mout', 243),
    ('NEW_VALLEY', 'FARAFRA', 'الفرافرة', 'Farafra', 'Farafra', 244),
    ('NEW_VALLEY', 'BALAT', 'بلاط', 'Balat', 'Balat', 245),
    ('NEW_VALLEY', 'DAKHLA', 'الداخلة', 'Dakhla', 'Dakhla', 246),
    ('SUEZ', 'SUEZ', 'السويس', 'Suez', 'Suez', 247),
    ('SUEZ', 'ALGANAYEN', 'الجناين', 'Alganayen', 'Alganayen', 248),
    ('SUEZ', 'ATAQAH', 'عتاقة', 'Ataqah', 'Ataqah', 249),
    ('SUEZ', 'AIN_SOKHNA', 'العين السخنة', 'Ain Sokhna', 'Ain Sokhna', 250),
    ('SUEZ', 'FAYSAL', 'فيصل', 'Faysal', 'Faysal', 251),
    ('ASWAN', 'ASWAN', 'أسوان', 'Aswan', 'Aswan', 252),
    ('ASWAN', 'ASWAN_EL_GEDIDA', 'أسوان الجديدة', 'Aswan El Gedida', 'Aswan El Gedida', 253),
    ('ASWAN', 'DRAU', 'دراو', 'Drau', 'Drau', 254),
    ('ASWAN', 'KOM_OMBO', 'كوم أمبو', 'Kom Ombo', 'Kom Ombo', 255),
    ('ASWAN', 'NASR_AL_NUBA', 'نصر النوبة', 'Nasr Al Nuba', 'Nasr Al Nuba', 256),
    ('ASWAN', 'KALABSHA', 'كلابشة', 'Kalabsha', 'Kalabsha', 257),
    ('ASWAN', 'EDFU', 'إدفو', 'Edfu', 'Edfu', 258),
    ('ASWAN', 'AL-RADISIYAH', 'الرديسية', 'Al-Radisiyah', 'Al-Radisiyah', 259),
    ('ASWAN', 'AL_BASILIA', 'البصيلية', 'Al Basilia', 'Al Basilia', 260),
    ('ASWAN', 'AL_SIBAEIA', 'السباعية', 'Al Sibaeia', 'Al Sibaeia', 261),
    ('ASWAN', 'ABO_SIMBL_AL_SIYAHIA', 'ابوسمبل السياحية', 'Abo Simbl Al Siyahia', 'Abo Simbl Al Siyahia', 262),
    ('ASWAN', 'MARSA_ALAM', 'مرسى علم', 'Marsa Alam', 'Marsa Alam', 263),
    ('ASSIUT', 'ASSIUT', 'أسيوط', 'Assiut', 'Assiut', 264),
    ('ASSIUT', 'ASSIUT_EL_GEDIDA', 'أسيوط الجديدة', 'Assiut El Gedida', 'Assiut El Gedida', 265),
    ('ASSIUT', 'DAYROUT', 'ديروط', 'Dayrout', 'Dayrout', 266),
    ('ASSIUT', 'MANFALUT', 'منفلوط', 'Manfalut', 'Manfalut', 267),
    ('ASSIUT', 'QUSIYA', 'القوصية', 'Qusiya', 'Qusiya', 268),
    ('ASSIUT', 'ABNOUB', 'أبنوب', 'Abnoub', 'Abnoub', 269),
    ('ASSIUT', 'ABU_TIG', 'أبو تيج', 'Abu Tig', 'Abu Tig', 270),
    ('ASSIUT', 'EL_GHANAIM', 'الغنايم', 'El Ghanaim', 'El Ghanaim', 271),
    ('ASSIUT', 'SAHEL_SELIM', 'ساحل سليم', 'Sahel Selim', 'Sahel Selim', 272),
    ('ASSIUT', 'EL_BADARI', 'البداري', 'El Badari', 'El Badari', 273),
    ('ASSIUT', 'SIDFA', 'صدفا', 'Sidfa', 'Sidfa', 274),
    ('BENI_SUEF', 'BANI_SWEIF', 'بني سويف', 'Bani Sweif', 'Bani Sweif', 275),
    ('BENI_SUEF', 'BENI_SUEF_EL_GEDIDA', 'بني سويف الجديدة', 'Beni Suef El Gedida', 'Beni Suef El Gedida', 276),
    ('BENI_SUEF', 'AL_WASTA', 'الواسطى', 'Al Wasta', 'Al Wasta', 277),
    ('BENI_SUEF', 'NASER', 'ناصر', 'Naser', 'Naser', 278),
    ('BENI_SUEF', 'EHNASIA', 'إهناسيا', 'Ehnasia', 'Ehnasia', 279),
    ('BENI_SUEF', 'BEBA', 'ببا', 'beba', 'beba', 280),
    ('BENI_SUEF', 'FASHN', 'الفشن', 'Fashn', 'Fashn', 281),
    ('BENI_SUEF', 'SOMASTA', 'سمسطا', 'Somasta', 'Somasta', 282),
    ('BENI_SUEF', 'ALABBASERI', 'الاباصيرى', 'Alabbaseri', 'Alabbaseri', 283),
    ('BENI_SUEF', 'MOKBEL', 'مقبل', 'Mokbel', 'Mokbel', 284),
    ('PORT_SAID', 'PORSAID', 'بورسعيد', 'PorSaid', 'PorSaid', 285),
    ('PORT_SAID', 'PORT_FOUAD', 'بورفؤاد', 'Port Fouad', 'Port Fouad', 286),
    ('PORT_SAID', 'ALARAB', 'العرب', 'Alarab', 'Alarab', 287),
    ('PORT_SAID', 'ZOHOUR', 'حى الزهور', 'Zohour', 'Zohour', 288),
    ('PORT_SAID', 'ALSHARQ', 'حى الشرق', 'Alsharq', 'Alsharq', 289),
    ('PORT_SAID', 'ALDAWAHI', 'حى الضواحى', 'Aldawahi', 'Aldawahi', 290),
    ('PORT_SAID', 'ALMANAKH', 'حى المناخ', 'Almanakh', 'Almanakh', 291),
    ('PORT_SAID', 'MUBARAK', 'حى مبارك', 'Mubarak', 'Mubarak', 292),
    ('DAMIETTA', 'DAMIETTA', 'دمياط', 'Damietta', 'Damietta', 293),
    ('DAMIETTA', 'NEW_DAMIETTA', 'دمياط الجديدة', 'New Damietta', 'New Damietta', 294),
    ('DAMIETTA', 'RAS_EL_BAR', 'رأس البر', 'Ras El Bar', 'Ras El Bar', 295),
    ('DAMIETTA', 'FARASKOUR', 'فارسكور', 'Faraskour', 'Faraskour', 296),
    ('DAMIETTA', 'ZARQA', 'الزرقا', 'Zarqa', 'Zarqa', 297),
    ('DAMIETTA', 'ALSARU', 'السرو', 'alsaru', 'alsaru', 298),
    ('DAMIETTA', 'ALRUWDA', 'الروضة', 'alruwda', 'alruwda', 299),
    ('DAMIETTA', 'KAFR_EL-BATIKH', 'كفر البطيخ', 'Kafr El-Batikh', 'Kafr El-Batikh', 300),
    ('DAMIETTA', 'AZBET_AL_BURG', 'عزبة البرج', 'Azbet Al Burg', 'Azbet Al Burg', 301),
    ('DAMIETTA', 'MEET_ABOU_GHALIB', 'ميت أبو غالب', 'Meet Abou Ghalib', 'Meet Abou Ghalib', 302),
    ('DAMIETTA', 'KAFR_SAAD', 'كفر سعد', 'Kafr Saad', 'Kafr Saad', 303),
    ('SHARKIA', 'ZAGAZIG', 'الزقازيق', 'Zagazig', 'Zagazig', 304),
    ('SHARKIA', 'AL_ASHR_MEN_RAMADAN', 'العاشر من رمضان', 'Al Ashr Men Ramadan', 'Al Ashr Men Ramadan', 305),
    ('SHARKIA', 'MINYA_AL_QAMH', 'منيا القمح', 'Minya Al Qamh', 'Minya Al Qamh', 306),
    ('SHARKIA', 'BELBEIS', 'بلبيس', 'Belbeis', 'Belbeis', 307),
    ('SHARKIA', 'MASHTOUL_EL_SOUQ', 'مشتول السوق', 'Mashtoul El Souq', 'Mashtoul El Souq', 308),
    ('SHARKIA', 'QENAIAT', 'القنايات', 'Qenaiat', 'Qenaiat', 309),
    ('SHARKIA', 'ABU_HAMMAD', 'أبو حماد', 'Abu Hammad', 'Abu Hammad', 310),
    ('SHARKIA', 'EL_QURAIN', 'القرين', 'El Qurain', 'El Qurain', 311),
    ('SHARKIA', 'HEHIA', 'ههيا', 'Hehia', 'Hehia', 312),
    ('SHARKIA', 'ABU_KABIR', 'أبو كبير', 'Abu Kabir', 'Abu Kabir', 313),
    ('SHARKIA', 'FACCUS', 'فاقوس', 'Faccus', 'Faccus', 314),
    ('SHARKIA', 'EL_SALIHIA_EL_GEDIDA', 'الصالحية الجديدة', 'El Salihia El Gedida', 'El Salihia El Gedida', 315),
    ('SHARKIA', 'AL_IBRAHIMIYAH', 'الإبراهيمية', 'Al Ibrahimiyah', 'Al Ibrahimiyah', 316),
    ('SHARKIA', 'DEIRB_NEGM', 'ديرب نجم', 'Deirb Negm', 'Deirb Negm', 317),
    ('SHARKIA', 'KAFR_SAQR', 'كفر صقر', 'Kafr Saqr', 'Kafr Saqr', 318),
    ('SHARKIA', 'AWLAD_SAQR', 'أولاد صقر', 'Awlad Saqr', 'Awlad Saqr', 319),
    ('SHARKIA', 'HUSSEINIYA', 'الحسينية', 'Husseiniya', 'Husseiniya', 320),
    ('SHARKIA', 'SAN_ALHAJAR_ALQABLIA', 'صان الحجر القبلية', 'san alhajar alqablia', 'san alhajar alqablia', 321),
    ('SHARKIA', 'MANSHAYAT_ABU_OMAR', 'منشأة أبو عمر', 'Manshayat Abu Omar', 'Manshayat Abu Omar', 322),
    ('SOUTH_SINAI', 'AL_TOOR', 'الطور', 'Al Toor', 'Al Toor', 323),
    ('SOUTH_SINAI', 'SHARM_EL-SHAIKH', 'شرم الشيخ', 'Sharm El-Shaikh', 'Sharm El-Shaikh', 324),
    ('SOUTH_SINAI', 'DAHAB', 'دهب', 'Dahab', 'Dahab', 325),
    ('SOUTH_SINAI', 'NUWEIBA', 'نويبع', 'Nuweiba', 'Nuweiba', 326),
    ('SOUTH_SINAI', 'TABA', 'طابا', 'Taba', 'Taba', 327),
    ('SOUTH_SINAI', 'SAINT_CATHERINE', 'سانت كاترين', 'Saint Catherine', 'Saint Catherine', 328),
    ('SOUTH_SINAI', 'ABU_REDIS', 'أبو رديس', 'Abu Redis', 'Abu Redis', 329),
    ('SOUTH_SINAI', 'ABU_ZENAIMA', 'أبو زنيمة', 'Abu Zenaima', 'Abu Zenaima', 330),
    ('SOUTH_SINAI', 'RAS_SIDR', 'رأس سدر', 'Ras Sidr', 'Ras Sidr', 331),
    ('KAFR_EL_SHEIKH', 'KAFR_EL_SHEIKH', 'كفر الشيخ', 'Kafr El Sheikh', 'Kafr El Sheikh', 332),
    ('KAFR_EL_SHEIKH', 'KAFR_EL_SHEIKH_DOWNTOWN', 'وسط البلد كفر الشيخ', 'Kafr El Sheikh Downtown', 'Kafr El Sheikh Downtown', 333),
    ('KAFR_EL_SHEIKH', 'DESOUQ', 'دسوق', 'Desouq', 'Desouq', 334),
    ('KAFR_EL_SHEIKH', 'FOOH', 'فوه', 'Fooh', 'Fooh', 335),
    ('KAFR_EL_SHEIKH', 'METOBAS', 'مطوبس', 'Metobas', 'Metobas', 336),
    ('KAFR_EL_SHEIKH', 'BURG_AL_BURULLUS', 'برج البرلس', 'Burg Al Burullus', 'Burg Al Burullus', 337),
    ('KAFR_EL_SHEIKH', 'BALTIM', 'بلطيم', 'Baltim', 'Baltim', 338),
    ('KAFR_EL_SHEIKH', 'MASIEF_BALTIM', 'مصيف بلطيم', 'Masief Baltim', 'Masief Baltim', 339),
    ('KAFR_EL_SHEIKH', 'HAMOL', 'الحامول', 'Hamol', 'Hamol', 340),
    ('KAFR_EL_SHEIKH', 'BELLA', 'بيلا', 'Bella', 'Bella', 341),
    ('KAFR_EL_SHEIKH', 'RIYADH', 'الرياض', 'Riyadh', 'Riyadh', 342),
    ('KAFR_EL_SHEIKH', 'SIDI_SALM', 'سيدي سالم', 'Sidi Salm', 'Sidi Salm', 343),
    ('KAFR_EL_SHEIKH', 'QELLEN', 'قلين', 'Qellen', 'Qellen', 344),
    ('KAFR_EL_SHEIKH', 'SIDI_GHAZI', 'سيدي غازي', 'Sidi Ghazi', 'Sidi Ghazi', 345),
    ('MATROUH', 'MARSA_MATROUH', 'مرسى مطروح', 'Marsa Matrouh', 'Marsa Matrouh', 346),
    ('MATROUH', 'EL_HAMAM', 'الحمام', 'El Hamam', 'El Hamam', 347),
    ('MATROUH', 'ALAMEIN', 'العلمين', 'Alamein', 'Alamein', 348),
    ('MATROUH', 'DABAA', 'الضبعة', 'Dabaa', 'Dabaa', 349),
    ('MATROUH', 'AL-NAGILA', 'النجيلة', 'Al-Nagila', 'Al-Nagila', 350),
    ('MATROUH', 'SIDI_BRANI', 'سيدي براني', 'Sidi Brani', 'Sidi Brani', 351),
    ('MATROUH', 'SALLOUM', 'السلوم', 'Salloum', 'Salloum', 352),
    ('MATROUH', 'SIWA', 'سيوة', 'Siwa', 'Siwa', 353),
    ('MATROUH', 'MARINA', 'مارينا', 'Marina', 'Marina', 354),
    ('MATROUH', 'NORTH_COAST', 'الساحل الشمالى', 'North Coast', 'North Coast', 355),
    ('LUXOR', 'LUXOR', 'الأقصر', 'Luxor', 'Luxor', 356),
    ('LUXOR', 'NEW_LUXOR', 'الأقصر الجديدة', 'New Luxor', 'New Luxor', 357),
    ('LUXOR', 'ESNA', 'إسنا', 'Esna', 'Esna', 358),
    ('LUXOR', 'NEW_TIBA', 'طيبة الجديدة', 'New Tiba', 'New Tiba', 359),
    ('LUXOR', 'AL_ZIYNIA', 'الزينية', 'Al ziynia', 'Al ziynia', 360),
    ('LUXOR', 'AL_BAYADIEH', 'البياضية', 'Al Bayadieh', 'Al Bayadieh', 361),
    ('LUXOR', 'AL_QARNA', 'القرنة', 'Al Qarna', 'Al Qarna', 362),
    ('LUXOR', 'ARMANT', 'أرمنت', 'Armant', 'Armant', 363),
    ('LUXOR', 'AL_TUD', 'الطود', 'Al Tud', 'Al Tud', 364),
    ('QENA', 'QENA', 'قنا', 'Qena', 'Qena', 365),
    ('QENA', 'NEW_QENA', 'قنا الجديدة', 'New Qena', 'New Qena', 366),
    ('QENA', 'ABU_TESHT', 'ابو طشت', 'Abu Tesht', 'Abu Tesht', 367),
    ('QENA', 'NAG_HAMMADI', 'نجع حمادي', 'Nag Hammadi', 'Nag Hammadi', 368),
    ('QENA', 'DESHNA', 'دشنا', 'Deshna', 'Deshna', 369),
    ('QENA', 'ALWAQF', 'الوقف', 'Alwaqf', 'Alwaqf', 370),
    ('QENA', 'QAFT', 'قفط', 'Qaft', 'Qaft', 371),
    ('QENA', 'NAQADA', 'نقادة', 'Naqada', 'Naqada', 372),
    ('QENA', 'FARSHOUT', 'فرشوط', 'Farshout', 'Farshout', 373),
    ('QENA', 'QUOS', 'قوص', 'Quos', 'Quos', 374),
    ('NORTH_SINAI', 'ARISH', 'العريش', 'Arish', 'Arish', 375),
    ('NORTH_SINAI', 'SHEIKH_ZOWAID', 'الشيخ زويد', 'Sheikh Zowaid', 'Sheikh Zowaid', 376),
    ('NORTH_SINAI', 'NAKHL', 'نخل', 'Nakhl', 'Nakhl', 377),
    ('NORTH_SINAI', 'RAFAH', 'رفح', 'Rafah', 'Rafah', 378),
    ('NORTH_SINAI', 'BIR_AL-ABED', 'بئر العبد', 'Bir al-Abed', 'Bir al-Abed', 379),
    ('NORTH_SINAI', 'AL_HASANA', 'الحسنة', 'Al Hasana', 'Al Hasana', 380),
    ('SOHAG', 'SOHAG', 'سوهاج', 'Sohag', 'Sohag', 381),
    ('SOHAG', 'SOHAG_EL_GEDIDA', 'سوهاج الجديدة', 'Sohag El Gedida', 'Sohag El Gedida', 382),
    ('SOHAG', 'AKHMEEM', 'أخميم', 'Akhmeem', 'Akhmeem', 383),
    ('SOHAG', 'AKHMIM_EL_GEDIDA', 'أخميم الجديدة', 'Akhmim El Gedida', 'Akhmim El Gedida', 384),
    ('SOHAG', 'ALBALINA', 'البلينا', 'Albalina', 'Albalina', 385),
    ('SOHAG', 'EL_MARAGHA', 'المراغة', 'El Maragha', 'El Maragha', 386),
    ('SOHAG', 'DAR_AISALAAM', 'دار السلام', 'Dar AISalaam', 'Dar AISalaam', 387),
    ('SOHAG', 'GERGA', 'جرجا', 'Gerga', 'Gerga', 388),
    ('SOHAG', 'JAHINA_AL_GHARBIA', 'جهينة الغربية', 'Jahina Al Gharbia', 'Jahina Al Gharbia', 389),
    ('SOHAG', 'SAQILATUH', 'ساقلته', 'Saqilatuh', 'Saqilatuh', 390),
    ('SOHAG', 'TAMA', 'طما', 'Tama', 'Tama', 391),
    ('SOHAG', 'TAHTA', 'طهطا', 'Tahta', 'Tahta', 392),
    ('SOHAG', 'ALKAWTHAR', 'الكوثر', 'Alkawthar', 'Alkawthar', 393)
)
INSERT INTO "CityLookup" ("governorateId", "key", "labelAr", "labelEn", "labelFr", "isActive", "sortOrder")
SELECT g."id", c."key", c."labelAr", c."labelEn", c."labelFr", true, c."sortOrder"
FROM cities c
JOIN "GovernorateLookup" g ON g."key" = c."governorateKey"
ON CONFLICT ("governorateId", "key") DO UPDATE
SET "labelAr" = EXCLUDED."labelAr",
    "labelEn" = EXCLUDED."labelEn",
    "labelFr" = EXCLUDED."labelFr",
    "isActive" = true,
    "sortOrder" = EXCLUDED."sortOrder",
    "updatedAt" = CURRENT_TIMESTAMP;
